### ISSUE TITLE
csi-blob-node Init:Error when it is enabled with node.enableBlobfuseProxy="true"

### ISSUE THREAD

**Issue by prabhumathiyalagan** [kubernetes-sigs/blob-csi-driver#1000]
Installing blob-csi-driver in AKS with node.enableBlobfuseProxy="true" is getting into error state. It is due to init container "install-blobfuse-proxy" running this command is failing "nsenter --mount=/proc/1/ns/mnt dpkg -i /etc/packages-microsoft-prod.deb"

The following packages will be DOWNGRADED:
blobfuse2
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 16 not upgraded.
E: Packages were downgraded and -y was used without --allow-downgrades.

**What happened**:
csi-blob-node-xxxxxx                    0/3     Init:Error   1 (13s ago)   19s

**What you expected to happen**:
Should be running fine with enableBlobfuseProxy="true" 

**How to reproduce it**:
Just run the installation

```sh
helm repo add blob-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts

helm upgrade --install blob-csi-driver blob-csi-driver/blob-csi-driver --set node.enableBlobfuseProxy="true" --namespace kube-system --version "v1.22.1" --set cloud=AzureStackCloud
```
**Anything else we need to know?**:
_Logs_
--- 
+ INSTALL_BLOBFUSE_PROXY=true
+ DISABLE_UPDATEDB=true
+ SET_MAX_OPEN_FILE_NUM=true
+ SET_READ_AHEAD_SIZE=true
+ READ_AHEAD_KB=15380
+ HOST_CMD=nsenter --mount=/proc/1/ns/mnt
+ nsenter --mount=/proc/1/ns/mnt cat /etc/os-release
+ grep ^ID=
+ tr -d "
+ cut -d= -f2
+ DISTRIBUTION=ubuntu
Linux distribution: ubuntu
+ echo Linux distribution: ubuntu
+ [ ubuntu = ubuntu ]
+ [ true = true ]
+ nsenter --mount=/proc/1/ns/mnt lsb_release -rs
Ubuntu release: 22.04
+ release=22.04
+ echo Ubuntu release: 22.04
+ expr 22.04 < 22.04
+ [ 0 -eq 1 ]
+ cp /blobfuse-proxy/packages-microsoft-prod-22.04.deb /host/etc/packages-microsoft-prod.deb
+ yes
+ nsenter --mount=/proc/1/ns/mnt dpkg -i /etc/packages-microsoft-prod.deb
(Reading database ... 64896 files and directories currently installed.)
Preparing to unpack .../packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-ubuntu22.04.1) over (1.0-ubuntu22.04.1) ...
Setting up packages-microsoft-prod (1.0-ubuntu22.04.1) ...
+ nsenter --mount=/proc/1/ns/mnt apt update

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Hit:1 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 https://packages.microsoft.com/ubuntu/22.04/prod testing InRelease
Hit:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
Reading package lists...
Building dependency tree...
Reading state information...
17 packages can be upgraded. Run 'apt list --upgradable' to see them.
+ pkg_list=
+ [ true = true ]
+ expr 22.04 < 22.04
+ [ 0 -eq 1 ]
+ [ true = true ]
+ expr 22.04 < 22.04
install fuse3 for blobfuse2, current release is 22.04
begin to install  fuse3 blobfuse2=2.0.3
+ [ 0 -eq 1 ]
+ echo install fuse3 for blobfuse2, current release is 22.04
+ pkg_list= fuse3
+ [ -z 2.0.3 ]
+ pkg_list= fuse3 blobfuse2=2.0.3
+ echo begin to install  fuse3 blobfuse2=2.0.3
+ nsenter --mount=/proc/1/ns/mnt apt-get install -y fuse3 blobfuse2=2.0.3
Reading package lists...
Building dependency tree...
Reading state information...
fuse3 is already the newest version (3.10.5-1build1).
The following packages were automatically installed and are no longer required:
  bc python3-automat python3-bcrypt python3-click python3-colorama
  python3-constantly python3-hamcrest python3-hyperlink python3-incremental
  python3-pyasn1 python3-pyasn1-modules python3-service-identity
  python3-twisted python3-zope.interface
Use 'apt autoremove' to remove them.
The following packages will be DOWNGRADED:
  blobfuse2
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 16 not upgraded.
E: Packages were downgraded and -y was used without --allow-downgrades.

**Environment**:

- CSI Driver version: v1.22.1
- Kubernetes version (use `kubectl version`): 1.26.6
- OS (e.g. from /etc/os-release): Ubuntu release: 22.04
- Kernel (e.g. `uname -a`): Linux  4.15.0-2077 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: helm
- Others: Impact is hug across all cluster, this was running fine last week(before Aug 25th).

**Comment by jmclong** [comment]
@prabhumathiyalagan, can you try using the workaround that Andy mentioned here?

https://github.com/kubernetes-sigs/blob-csi-driver/issues/998#issuecomment-1695693285

**Comment by prabhumathiyalagan** [comment]
Yes this helps, appreciate your quick response.
