### ISSUE TITLE
failed to initialize new pipeline [config error in azstorage [account name not provided]]

### ISSUE THREAD

**Issue by mahammadadamalli** [kubernetes-sigs/blob-csi-driver#1030]
Want to configure csi.blob.azure.com driver in place of flexvolume because its has been deprecated in 1.25.11 Kubernets version but getting below error. Could you please suggest how we can fixed this issue.

- csi:
          driver: blob.csi.azure.com
          readOnly: false
          volumeAttributes:
            containerName: agent-shared
            secretName: storage-secret

**code = Unknown desc = exit status 1 Error: failed to initialize new pipeline [config error in azstorage [account name not provided]]
, output:**

**Comment by andyzhangx** [comment]
how did you create the `storage-secret` secret, error msg shows that you did not set account name in the secret, here is an example:

```console
kubectl create secret generic storage-secret --from-literal=azurestorageaccountname="xxx" --from-literal azurestorageaccountkey="xxx" --type=Opaque
```

**Comment by mahammadadamalli** [comment]
@andyzhangx Yes secret is already created and passed too in statefulset file. i am trying to pass this value in both the way

Option 1:-
csi:
driver: blob.csi.azure.com
readOnly: false
volumeAttributes:
containerName: agent-shared
secretName: storage-secret

Warning  FailedMount  3m25s (x50 over 89m)  kubelet  MountVolume.SetUp failed for volume "centrald1-sftp-volume" : rpc error: code = Internal desc = Mount failed with error: rpc error: code = Unknown desc = exit status 1 Error: failed to initialize new pipeline [config error in azstorage [account name not provided]]
, output:



Option 2:
Error from server (BadRequest): error when creating "np-euw-666-agentstageref.yaml": StatefulSet in version "v1" cannot be handled as a StatefulSet: strict decoding error: unknown field "spec.template.spec.volumes[1].csi.nodeStageSecretRef"

csi:
driver: blob.csi.azure.com
readOnly: false
volumeAttributes:
    containerName: agent-shared
nodeStageSecretRef:
    name: storage-secret
    namespace: azp-agent

**Comment by andyzhangx** [comment]
not sure whether you have set `azurestorageaccountname` correctly in the `storage-secret`, you could set `storageAccount` in `volumeAttributes`, and if you could not set `azurestorageaccountkey` correctly in the `storage-secret`, you will still get another error.

```
csi:
  driver: blob.csi.azure.com
  readOnly: false
  volumeAttributes:
    containerName: agent-shared
    secretName: storage-secret
    storageAccount: xxx
```

**Comment by mahammadadamalli** [comment]
After recreating the secret via manually its working fine . kubectl create secret generic storage-secret --from-literal=azurestorageaccountname="xxx" --from-literal azurestorageaccountkey="xxx" --type=Opaque


But when i am trying to deploy via helm its getting the same error.
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: storage-secret
  namespace: {{ .Release.Namespace }}
data:
  accountkey: {{ .Values.SAAccessKey | b64enc }}
  accountname: {{ .Values.SAName | b64enc }}

**Comment by andyzhangx** [comment]
correct field names should be:
```
azurestorageaccountname
azurestorageaccountkey
```
