### ISSUE TITLE
wrong command to check Azure Blob Storage CSI driver pods status

### ISSUE THREAD

**Issue by bessalahAmar** [kubernetes-sigs/blob-csi-driver#1070]
**What happened**:

To check Azure Blob Storage CSI driver pods status , please run:
kubectl --namespace=csi-azure-blob get pods --selector="release=blob-csi-driver" --watch

![image](https://github.com/kubernetes-sigs/blob-csi-driver/assets/36238279/fe488b12-a602-4c6e-ae32-42c2eb8f711c)

the csi-blob pod don't have the label release=blob-csi-driver

![image](https://github.com/kubernetes-sigs/blob-csi-driver/assets/36238279/e7ccd1dd-7ee9-46a9-af99-f4caf6f71e26)

**What you expected to happen**:

see the list of create pod and their status

**How to reproduce it**:

install the helm chart and run :
kubectl --namespace=csi-azure-blob get pods --selector="release=blob-csi-driver" --watch

**Anything else we need to know?**:

instead we can use : 
kubectl --namespace=csi-azure-blob get pods --selector="app.kubernetes.io/name=blob-csi-driver" --watch

**Environment**:

- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
@umagnus could you check this issue and also work out a doc PR? thanks.
