### ISSUE TITLE
Updating the csi-driver causes all mounted blob to lose their connections

### ISSUE THREAD

**Issue by Sartigan** [kubernetes-sigs/blob-csi-driver#1128]
**What happened**: After updating the csi-driver to a new version all pods already using the csi driver lose their connections.

**What you expected to happen**: Connection remains intact

**How to reproduce it**:
1. Install csi-blob with version n-1
2. Create a Pod with a csi-driver mount
3. helm upgrade (wait to finish rollout)
4. LSing into the mounted directory will return an error

**Environment**: All environments

- CSI Driver version: blob-csi: v1.23.1
- Kubernetes version (use `kubectl version`): 1.24.13
- OS (e.g. from /etc/os-release): Rocky Linux 8.8
- Kernel (e.g. `uname -a`): 4.18.0-477.27.1.el8_8.x86_64
- Install tools: helm

**Comment by andyzhangx** [comment]
if you have already deployed blob csi driver with blobfuse-proxy enabled, then upgrading the csi driver won't make existing connections invalid: https://github.com/kubernetes-sigs/blob-csi-driver/tree/master/deploy/blobfuse-proxy, you could find more details in the blobfuse-proxy link.
