### ISSUE TITLE
Init Container returns with a non-zero causing the helm chart to fail

### ISSUE THREAD

**Issue by jstralko** [kubernetes-sigs/blob-csi-driver#1153]
**What happened**:

When installing the  csi-blob helm chart on a new 1.27.3 Kubernetes cluster the csi-blob daemonset fail to start.  The pods fail to start and immediately go into Init:CrashLoopBackOff state.  Digging into the init container the following script returns a non-zero: /blobfuse-proxy/init.sh

Here's the output:

The following packages will be DOWNGRADED:
  blobfuse2
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 55 not upgraded.
E: Packages were downgraded and -y was used without --allow-downgrades.

**What you expected to happen**:

I expect the init container to return a zero so the pods can get in Running state.

**Environment**:
kubectl get po -o yaml | grep mcr | grep blob
      image: mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.23.2
      image: mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.23.2
      imageID: mcr.microsoft.com/oss/kubernetes-csi/blob-csi@sha256:31854ed041f1d59f8210976fa2b71e39b0628d9d3ff868a46d444d7fcf401fb7

- CSI Driver version: 1.23.2
- Kubernetes version (use `kubectl version`):
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3

**Comment by jmclong** [comment]
I'm sorry that you're experiencing this issue with the csi-blob daemonset.

@jstralko, can you try using the workaround that Andy mentioned here? This should skip installing blobfuse2

https://github.com/kubernetes-sigs/blob-csi-driver/issues/998#issuecomment-1695693285

**Comment by jstralko** [comment]
Thank you, i will try that now.  That is a much better workaround then what i'm doing now. I was patching the initContainer with this: 
`
        - command: ["/bin/sh","-c"]
          args: ["/blobfuse-proxy/init.sh || true"]
`

**Comment by jstralko** [comment]
FYI: to fix my automation (in terraform) i was able to install the helm chart with the following value: 
`node.blobfuseProxy.installBlobfuse2` to false

**Comment by andyzhangx** [comment]
if you could update the charts repo, it works now with blobfuse v2.1.2 installed by default
