### ISSUE TITLE
nconnect mount option does not work with aznfs mount in Azure linux distro

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/blob-csi-driver#1269]
**What happened**:

nconnect mount option does not work with aznfs mount in Azure linux distro

Customer recently migrated AKS connection to blob storage using driver: blob.csi.azure.com
 
On PV, the mount option below was working when initially implemented:
 
mountOptions:
 - nconnect=4
 
Then customer also migrated node from Ubuntu 'AKSUbuntu-2204gen2containerd-202402.07.0' to Azure Linux container 'AKSCBLMariner-V2gen2-202402.07.0'
 
When migrated to azure linux container, this mount option nconnect stopped working with following error:
 
"Events:
 Type    Reason       Age                        From     Message
 ----    ------       ----                       ----     -------
 Warning FailedMount  invalid (x53 over 105m)  kubelet  MountVolume.MountDevice failed for volume 'pv-storageaccount-scan-storage' : rpc error: code = Internal desc = volume(storageaccount_scan-storage) mount 'storageaccount.blob.core.windows.net:/storageaccount/scan-storage' on '/var/lib/kubelet/plugins/kubernetes.io/csi/blob.csi.azure.com/8a489e0c9e233fe5a00d534e8902b988a4aa747978adaabd93c13d09ccb64ebb/globalmount' failed with mount failed: exit status 1
Mounting command: mount
Mounting arguments: -t aznfs -o nconnect=4,sec=sys,vers=3,nolock storageaccount.blob.core.windows.net:/storageaccount/scan-storage /var/lib/kubelet/plugins/kubernetes.io/csi/blob.csi.azure.com/8a489e0c9e233fe5a00d534e8902b988a4aa747978adaabd93c13d09ccb64ebb/globalmount
Output: /opt/microsoft/aznfs/mountscript.sh: line 80: modprobe: command not found
nconnect option needs NFS client with Azure nconnect support!
Mount failed!
Please refer to http://aka.ms/blobmounterror for possible causes and solutions for mount errors. "

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:

- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cvvz** [comment]
We need to figure out why there is no `/sys/module/sunrpc/parameters/enable_azure_nconnect` on Azure Linux, since without this  file, we can't mount using `nconnect` option. https://github.com/Azure/AZNFS-mount/blob/0f39ec4bad59d94bbc8af4ef1bf11823c9c590a4/src/mountscript.sh#L81C23-L81C74

**Comment by andyzhangx** [comment]
after confirm with blob nfs v3 team, nconect on Azure Linux is not supported, if users want to use nconnect option to improve perf, then they need to use Ubunut node

**Comment by andyzhangx** [comment]
> hi [@andyzhangx](https://github.com/andyzhangx) where is that limitation documented?
> 
> I found it by accident here: https://github.com/kubernetes-sigs/blob-csi-driver/tree/master/deploy/example/nfs
> 
> Maybe should be here? https://docs.azure.cn/en-us//storage/blobs/network-file-system-protocol-support-performance#increase-the-number-of-tcp-connections

@TiloGit we have mentioned here in the example:
https://github.com/kubernetes-sigs/blob-csi-driver/blob/7fc419398b5cb7fb0f2ec89e1a1766d83a773266/deploy/example/storageclass-blob-nfs.yaml#L11-L12

**Comment by andyzhangx** [comment]
and also here: https://github.com/kubernetes-sigs/blob-csi-driver/tree/master/deploy/example/nfs#how-to-use-nfs-feature

**Comment by TiloGit** [comment]
thanks, I think would be great to have it on the official Microsoft Documentation pages 

btw does **Azure Linux 3.0** change this limitation? https://github.com/microsoft/azurelinux/releases/tag/3.0.20240727-3.0

**Comment by andyzhangx** [comment]
> thanks, I think would be great to have it on the official Microsoft Documentation pages
> 
> btw does **Azure Linux 3.0** change this limitation? https://github.com/microsoft/azurelinux/releases/tag/3.0.20240727-3.0

Azure Linux 3.0 does not support nconnect mount option either.
