### ISSUE TITLE
Failing install-blobfuse-proxy init container since helm chart version v1.23.2

### ISSUE THREAD

**Issue by CKnoppas** [kubernetes-sigs/blob-csi-driver#1275]
**What happened**:
When installing the driver with helm chart version v1.23.2 the init container from the csi-blob-node pod fails see the logs from the container:
```+ INSTALL_BLOBFUSE_PROXY=false
+ DISABLE_UPDATEDB=true
+ SET_MAX_OPEN_FILE_NUM=true
+ SET_READ_AHEAD_SIZE=true
+ READ_AHEAD_KB=15380
+ HOST_CMD=nsenter --mount=/proc/1/ns/mnt
+ nsenter --mount=/proc/1/ns/mnt cat /etc/os-release
+ grep ^ID=
+ cut -d= -f2
+ tr -d "
+ DISTRIBUTION=ubuntu
+ nsenter --mount=/proc/1/ns/mnt uname -m
Linux distribution: ubuntu, Arch: x86_64
+ ARCH=x86_64
+ echo Linux distribution: ubuntu, Arch: x86_64
+ . ./blobfuse-proxy/install-proxy-ubuntu.sh
+ set -xe
start to install blobfuse/blobfuse2....
+ [ x86_64 = aarch64 ]
+ [ true = true ]
+ echo start to install blobfuse/blobfuse2....
+ nsenter --mount=/proc/1/ns/mnt lsb_release -rs
nsenter: failed to execute lsb_release: No such file or directory
+ release=
```
**What you expected to happen**:
The init container should be able to find lsb_release.
**How to reproduce it**:
`helm install blob-csi-driver blob-csi-driver/blob-csi-driver --namespace kube-system --version v1.23.2 --set node.enableBlobfuseProxy=false`

**Anything else we need to know?**:
I recognized that the container registry repo changed but not sure if this is linked to the observed behaviour: 
https://github.com/kubernetes-sigs/blob-csi-driver/pull/1255/commits/6c75764aa886eda01c92b50b027b2fe6ef511225#diff-057fe338a0577894529020dfa3c652ea10430ce62d937cfd6ee21c277327d974 
**Environment**:
- CSI Driver version: blob-csi:v1.23.2
- Kubernetes version: v1.26.5 (minikube container)
- OS (e.g. from /etc/os-release): Ubuntu 20.04.6 LTS
- Kernel : Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64 x86_64 GNU/Linux 
- Install tools: helm
- Others:

**Comment by andyzhangx** [comment]
@CKnoppas we don't have e2e tests running on Ubuntu 20.04, the upstream e2e tests is running on Ubuntu 18.04 and 22.04.
What's the output of `whereis lsb_release` on the node?

**Comment by CKnoppas** [comment]
```
whereis lsb_release
lsb_release:

lsb_release -a
-bash: lsb_release: command not found
```
thanks for the hint! seems like a minikube problem, i will look into it and report. 
strange enough i tested the driver within minikube node successfully before the 1.24.0 release.
