### ISSUE TITLE
Can this be used on the open source Kubenetes?

### ISSUE THREAD

**Issue by dxygit1** [kubernetes-sigs/blob-csi-driver#1407]
Can this be used on the open source Kubenetes?

**Comment by andyzhangx** [comment]
yes, pls follow this guide to set cloud provider config: https://github.com/kubernetes-sigs/blob-csi-driver?tab=readme-ov-file#option1-provide-cloud-provider-config-with-azure-credentials

**Comment by dxygit1** [comment]
Ok, thank you very much.
