### ISSUE TITLE
After the AKS node image was upgraded, the csi driver daemonset csi-blob-node failed to start

### ISSUE THREAD

**Issue by LeoandHenry** [kubernetes-sigs/blob-csi-driver#1507]
1. Background:
The customer used helm to install the csi driver before, and found that the pod of CSI-BLOB-Node could not start normally after an AKS node image upgrade.
Installation link for customer reference: https://github.com/kubernetes-sigs/blob-csi-driver/tree/master/charts

2. AKS Cluster Information
1)cluster version:1.27.9
2)CSI driver version:1.23.3
3)AKS node image version:AKSUbuntu-2204gen2containerd-202407.03.0
4）Storage class：
![image](https://github.com/user-attachments/assets/03d822e3-2a65-4a0f-a556-19da8534a389)
5）daemonset: csi-blob-node
![image](https://github.com/user-attachments/assets/22d1b20f-4d62-4e72-b377-e408a91dc861)

3.Problem screenshot：
![image](https://github.com/user-attachments/assets/3e931769-6e5f-4869-9a58-770fc0fe475f)

![image](https://github.com/user-attachments/assets/af2c30f5-93a4-4813-9a0a-090050ee989c)

4.Expectation：
Please guide how to restore the daemonset csi-blob-node to running state in this case, and help  analyze the cause of the problem, thank you very much.

```[tasklist]
### Tasks
```

**Comment by andyzhangx** [comment]
pls disable `INSTALL_BLOBFUSE2` in the blob csi driver daemonset by running following command:
```
kubectl patch daemonset csi-blob-node -n kube-system -p '{"spec":{"template":{"spec":{"initContainers":[{"env":[{"name":"INSTALL_BLOBFUSE2","value":"false"},{"name":"BLOBFUSE2_VERSION","value":"2.3.0"}],"name":"install-blobfuse-proxy"}]}}}}'
```

**Comment by LeoandHenry** [comment]
Hi, @andyzhangx 
Thank you for your reply, can I just use "kubectl edit daemonset csi-blob-node -n kube-system" to set INSTALL_BLOBFUSE2=false?

And could you explain the reason for doing it in this way? thank you!

**Comment by andyzhangx** [comment]
yes, and new node image has already installed blobfuse 2.3.0, that could be the reason why initContainer is crashing

**Comment by LeoandHenry** [comment]
Thank you very much @andyzhangx.
But when use above command "kubectl patch daemonset csi-blob-node -n kube-system -p '{"spec":{"template":{"spec":{"initContainers":[{"env":[{"name":"INSTALL_BLOBFUSE2","value":"false"},{"name":"BLOBFUSE2_VERSION","value":"2.3.0"}],"name":"install-blobfuse-proxy"}]}}}}'" the daemonset still has problems:

![image](https://github.com/user-attachments/assets/0ab66585-be1c-4884-839e-26ebf1092d2f)
when I check the logs of the liveness-probe container, It shows that  29632 occupied. However, when I went to ont of  the aks node, there were liveness probes that were used at that port, and even if I killed the process, it would restart immediately:
![image](https://github.com/user-attachments/assets/e709bb0c-2906-400b-a7d4-9b823d6a2b73)
![image](https://github.com/user-attachments/assets/c4c7a0f0-2631-4cd3-bc47-5e66a45716ed)

One more thing that needs to be synchronized with you: The csi-blob-node pod can start successfully after the customer uses the csi driver version 1.24.2 without setting INSTALL_BLOBFUSE2=false. I have tested this locally, so the customer wants to know why this is the case. Are there any changes in the 1.24.2 version?
![image](https://github.com/user-attachments/assets/2efa1115-91ee-425b-9326-722d981a8efa)

**Comment by LeoandHenry** [comment]
By the way, in version 1.24.2, INSTALL_BLOBFUSE2 is true:
![image](https://github.com/user-attachments/assets/05535674-8261-4d7e-9545-64743882ed40)

**Comment by andyzhangx** [comment]
@LeoandHenry `INSTALL_BLOBFUSE2` should be set as false on aks node, while it should set as true on non-aks node since those nodes has not installed blobfuse2 by default.

**Comment by andyzhangx** [comment]
`1.24.2` chart has blobfuse 2.3.0 installed by default, so v1.24.2 works

**Comment by LeoandHenry** [comment]
Hi @andyzhangx ,If a newer version of csi driver such as 1.24.2 is installed, but the AKS node image is older and the blobfuse2 version on it is also old, such as 2.2.1, will csi-blob-node run properly?

**Comment by andyzhangx** [comment]
since aks node has already blobfuse2 binary installed, you should set `--set node.blobfuseProxy.installBlobfuse2=false` in helm chart install, so no matter what csi driver version you are going to install, it won't crash.

**Comment by LeoandHenry** [comment]
@andyzhangx  thank you so much, I got it.
