### ISSUE TITLE
How can we down-load the docker image associated with the Driver 

### ISSUE THREAD

**Issue by ktdharan** [kubernetes-sigs/blob-csi-driver#1531]
We are having our own-custom helm-chart that was developed for internal usage when using the [blob-csi-driver](https://github.com/kubernetes-sigs/blob-csi-driver), where can we download the current version of docker images used? MCR registry doesn't seem to have them hosted?

**Comment by andyzhangx** [comment]
@ktdharan you could build you own image by running `make container` or use latest image of master branch `mcr.microsoft.com/k8s/csi/blob-csi:latest`
