### ISSUE TITLE
Install blobfuse2 when using ARM64

### ISSUE THREAD

**Issue by explsd** [kubernetes-sigs/blob-csi-driver#1618]
**Is your feature request related to a problem?/Why is this needed**
Storage using bobfuse2 fails to mount when using ARM64 Oracle Linux. This is because blobfuse2 is not present on the node daemonset containers, since its installation is skipped when the architecture is ARM64.  https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/pkg/blobplugin/Dockerfile#L69 https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/pkg/blobfuse-proxy/install-proxy.sh#L25

**Describe the solution you'd like in detail**
Since [blobfuse2 now supports ARM64](https://github.com/Azure/azure-storage-fuse/wiki/Blobfuse2-Supported-Platforms) it should get installed when using ARM64 and specifying blobfuse2 to be installed.

**Describe alternatives you've considered**
Using helm post rendering to add an init container to the node pod on the helm chart that installs blobfuse2

**Comment by explsd** [comment]
I hacked around by using helm post rendering to overwrite the command and args so that the container first installs blobfuse2 before calling blobplugin

**Comment by andyzhangx** [comment]
@explsd thanks for the info, do you have interest to raise a PR to fix this issue on arm64?

**Comment by explsd** [comment]
@andyzhangx Sure. I think my plan would be to just add another architecture check in the Dockerfile, that would then install what works for ARM64
