### ISSUE TITLE
Confusing error log regarding the character `#` in `volumeHandle`

### ISSUE THREAD

**Issue by JoeyC-Dev** [kubernetes-sigs/blob-csi-driver#1619]
**Is your feature request related to a problem?/Why is this needed**

Log message is conflicted with official demo. 
This does not actually affect the running, but confusing. So I reported this as "Enhancement Request".

**Describe the solution you'd like in detail**

When I tried to export the log for debugging, I found the following log:
```text
I1003 04:20:17.851051    6943 blob.go:457] parsing volumeID(myblob-pv-1234-567-890-1234) return with error: error parsing volume id: "myblob-pv-1234-567-890-1234", should at least contain two #
```
This log is got via the following command:
```bash
kubectl logs csi-blob-node-abcdef -c blob -n kube-system
```

However, in the demo, it says:
https://github.com/kubernetes-sigs/blob-csi-driver/blob/7f8a70af1ca196a3e6a626a451fddcc83f694701/deploy/example/e2e_usage.md?plain=1#L96

It is way too confusing. If `#` is needed, why in official demo, it says "the # character is reserved for internal use"

**Ask:** clarify if `#` is really needed, and what should be the recommended way to name `volumeID`.

**Comment by Jackbennett** [comment]
Missed one: https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/blobfuse-mi/README.md?plain=1#L85-L86

But I did add the `#`'s to my manually assigned pv which cleared that error.

What's this supposed to be for? You have accountName & containerName required in the volumeAttributes it's wierd to even write this out.
