### ISSUE TITLE
BlobCSI Driver Sync Fails Post Server/VM Reboot | Requires PV/PVC Recreation with Unique Volume_Handle

### ISSUE THREAD

**Issue by Hidayathullashaik** [kubernetes-sigs/blob-csi-driver#1713]
Hi Team,

I am referencing the issue logged earlier: [Blobfuse CSI Configurations Issue #1620](https://github.com/kubernetes-sigs/blob-csi-driver/issues/1620).

[Problem Statement]
I have ensured that the volume_handle name is unique across Kubernetes clusters. However, after a planned or sudden reboot of a node/server, the Blobfuse CSI driver stops syncing to the Azure Storage Account. This forces me to delete the existing Persistent Volume (PV) and Persistent Volume Claim (PVC) and recreate them with a new volume_handle in the Kubernetes PV YAML file.

[Expected Behavior]
The Blobfuse CSI driver should automatically remount to the Azure Storage Account using the Blob configurations and storage account secrets whenever the server reboots.

Please advise on resolving this issue or if there are additional configurations needed to ensure the remount process works seamlessly post-reboot.

**Comment by andyzhangx** [comment]
@Hidayathullashaik before you reboot the VM, you should reschedule the pods with blobfuse volume to other nodes, otherwise the mounted blobfuse volume path could turn to be a local disk path, that's a known k8s kubelet bug, not sure whether they have solved in latest k8s version.

**Comment by Hidayathullashaik** [comment]
I wanted to update you on the resolution for the Blobfuse volume mount issue.

After logging a ticket with Microsoft, it was identified that the problem was due to a time mismatch on the server/VM/system. The lag in time caused the Blobfuse volume mount request header to be considered too old, resulting in a failure to mount.

Once we corrected the system time on the VM, we were able to successfully mount the volumes using both: Blobfuse2 commands and K3s persistent volumes

The issue now appears to be resolved.

@andyzhangx  - Thankyou for support. You can close this case.

**Comment by Hidayathullashaik** [comment]
As described in the previous comment. Hence closing the case
