### ISSUE TITLE
folders not being recognized when a octet-stream zero sized file with the same name in the same level

### ISSUE THREAD

**Issue by onepos-zaika** [kubernetes-sigs/blob-csi-driver#235]
AKS version: v1.17.9
blob-csi-driver installed via helm3: v0.8.0

installation command:
 helm3 install blob-csi-driver blob-csi-driver/blob-csi-driver --set controller.replicas=1 --namespace kube-system --version v0.8.0

problem description:
We have an existing blob container connecting to a VM and we are trying to migrate the workload to AKS.

We have successfully mounted the blob storage using blob-csi-driver using the PV and PVC approach. When we do a ls in a folder, most of the result are in duplication. When I view the container in azure portal storage explorer, I can see many folders listed with a zero sized octet-stream file of the same name. After some google search, it is a normal behaviour of blobfuse.

The blobfuse version in our original VM is 1.2.3 running in a Ubuntu machine.

Is it a bug or is it because the blobfuse version in blob-csi-driver is not compatible with blobfuse?
Thank you.

**Comment by andyzhangx** [comment]
hi @onepos-zaika the driver only use the built-in blobfuse binary, for v0.8.0, it's using `1.3.1`
cc @NaraVen for any insight about this issue, it's more like blobfuse driver issue.

**Comment by andyzhangx** [comment]
@onepos-zaika here is the way to install blobfuse `1.3.1` version on every agent node, that would help narrow down the issue:
```
k apply -f https://raw.githubusercontent.com/Azure/kubernetes-volume-drivers/master/flexvolume/blobfuse/binary/sysctl-install-blobfuse-1.3.1.yaml
```

also to narrow down this issue, use blobfuse mount directly on one agent node:
```
mkdir test
export AZURE_STORAGE_ACCOUNT=
export AZURE_STORAGE_ACCESS_KEY=
blobfuse test --container-name=CONTAINER-NAME --tmp-path=/tmp/blobfuse -o allow_other --file-cache-timeout-in-seconds=120
```

**Comment by NaraVen** [comment]
It is normal. The purpose of this is to provide a zero byte directory marker for empty directories since blob ( non-adls) has no other way to retain empty folders. So,  folders created in the mount dir or sub directory of blobfuse also have a zero file with the same name. The metadata hdi_isfolder=true is set in these files. However blobfuse will still work correctly  if the user decides to delete these folders once the directory has files or directories within it.

**Comment by onepos-zaika** [comment]
Hello! Thank you for the quick reply @andyzhangx  . Last night, I tried to compile blobfuse in a alpine docker image but failed... then I tried debian but it reported /dev/fuse not found...   I shall try blobfuse 1.3.1 in another ubuntu machine today. 

And @NaraVen, thank you for your insight. I know that is normal to have both the folder and a zero. But when I connect the existing blob using blob-csi-driver and ls into it, it shows two files with the same name. Then I cannot cd into the folder. But if I delete the zero file from azure portal, I can then cd into the folder...     I shall test it more today. Thank you.

**Comment by onepos-zaika** [comment]
hello all!
Finally.. the problem is because I have cloned the blob container using azure data factory....  It looks like that data factory will not preserve something so that the destination blob will have this problem....
I have to find another way to copy the blob to the new region later.  Thank you for your help. @andyzhangx  and @NaraVen

**Comment by andyzhangx** [comment]
thanks for the confirm

**Comment by NaraVen** [comment]
onepos-zaika , Glad you resolved the problem. However, I want to answer your question in case someone refers to this thread in future.  In blobfuse mounted dir you will be able to 'cd' to a directory whether you delete the zero byte directory marker blob or not.

**Comment by onepos-zaika** [comment]
Yes. Confirmed that,  In blobfuse mounted dir you will be able to 'cd' to a directory whether you delete the zero byte directory marker blob or not.
The captioned problem is caused by using azure data factory to move storage account which is a recommended method in azure document.
https://docs.microsoft.com/en-us/azure/storage/common/storage-account-move?tabs=azure-portal
under Copy data to or from Azure Blob storage by using Azure Data Factory

But I do not know where to report this problem.
