### ISSUE TITLE
Helm package gives Error: Invalid Semantic Version

### ISSUE THREAD

**Issue by songjiaxun** [kubernetes-sigs/blob-csi-driver#278]
**What happened**:
`helm package blob-csi-driver` under `latest` folder gives `Error: Invalid Semantic Version`.
Helm version: version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
so it does not work on helm `v3.4.1` now?

**Comment by songjiaxun** [comment]
> so it does not work on helm `v3.4.1` now?

It still does not work on helm `v3.4.1`. Probably we can just skip `helm package`? Submitted a PR already.

**Comment by andyzhangx** [comment]
this issue would be fixed by https://github.com/kubernetes-sigs/blob-csi-driver/pull/333, I changed the `version` to `1.0.0`, it would work, and need to update the version num in every new release.
