### ISSUE TITLE
Remove the dependency of azure.json in node server

### ISSUE THREAD

**Issue by ZeroMagic** [kubernetes-sigs/blob-csi-driver#284]
**Is your feature request related to a problem?/Why is this needed**

If the customers just use the node server to automatically complete the mount command, they don't need to provide the azure.json. But now, in our code, it is still required to provide the config.
After removing the config, the node server will also work on the non-AKS clusters in static provision.
**Describe the solution you'd like in detail**

**Describe alternatives you've considered**

**Additional context**

**Comment by ZeroMagic** [comment]
- [x] Feature Code 

- [ ] Feature Doc

**Comment by andyzhangx** [comment]
azure.json is not a dependency for both controller and node servers now.
