### ISSUE TITLE
Huge storage account list usage (cost a lot of money$$$)

### ISSUE THREAD

**Issue by onepos-zaika** [kubernetes-sigs/blob-csi-driver#289]
Hello!
We are using blob-csi-driver installed by helm chart blob-csi-driver-v0.10.0 in AKS cluster version 1.19.3
We have 400 pods in the cluster and each of them mounts to the same storage account 4 times.
It looks like that, when a pod is created, it generates a few thousand list operations... and when it times 400 pods, it becomes a few million list operations... 

![Screenshot 2020-12-07 100252](https://user-images.githubusercontent.com/50311058/101301947-47b05680-3875-11eb-9624-d2d6a049f6dd.jpg)

Is there a way for me to see where do the list operations come from? Thank you.
I have also opened a ticket in Azure to ask about that.

**Comment by andyzhangx** [comment]
@NaraVen do you have any idea on this?

**Comment by andyzhangx** [comment]
@onepos-zaika it's list operation in that account, right? should not be so many `storage account list` operations

**Comment by onepos-zaika** [comment]
@andyzhangx  Thank you for the prompt reply.
According to the azure cost analysis, it comes from lrs list and create container operations..
![Screenshot 2020-12-07 103046](https://user-images.githubusercontent.com/50311058/101302769-7d563f00-3877-11eb-9bac-4a0ffadd1f99.jpg)

**Comment by andyzhangx** [comment]
@onepos-zaika how many containers have you created totally? I am not clear about lrs list

**Comment by onepos-zaika** [comment]
We have around 400pods..  over 800 containers.
![Screenshot 2020-12-07 104546](https://user-images.githubusercontent.com/50311058/101303701-9364ff00-3879-11eb-8a31-c796cd1bfdfe.jpg)

We expect to growth to a few thousands next year.

**Comment by NaraVen** [comment]
Blobfuse does not automatically do a list after authenticating. Does the CSI driver have a default list to smoke test if the driver mounted? If it does then it should be changed to list only 10 or something because, if there are too many blobs List will be expensive: PayGo pricing of $0.05/10k operations (same as Hot/cool/archive).  Write is only 0.0175 per 10k and read 0.0014 per 10k.

**Comment by andyzhangx** [comment]
the driver won't list automatically, per the description: `when a pod is created, it generates a few thousand list operations`, @onepos-zaika will you app try to list all blobs in the start up?

**Comment by onepos-zaika** [comment]
The applicate does check for the existing of a file and if the file exist, we will compare the file with the source in docker image. If they are different and newer, we shall replace this file.  But it will not do this a few thousand times...  I am asking azure support to see whether I can have a log to see which file(s) are involved in the the operation.
Is there a way to log the csi operation in the driver?
Yes. the blob list price is expensive. Hopefully we can find the root cause soon. Thank you.

**Comment by andyzhangx** [comment]
@onepos-zaika you could see all operations in driver side here: https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/pkg/blob/nodeserver.go, there is no such list operation in that file.

**Comment by onepos-zaika** [comment]
Then..   maybe this is blobfuse's job to translate cp, mkdir commands to blob commands?
When contain starts, it will run a bash script like this:
if [ ! -d "${DIRPRIVATE}html" ]
then 
    mkdir -p "${DIRPRIVATE}html"
    cp -ru "$WWW_PATH/htmlorig"/* "${DIRPRIVATE}html"
fi

**Comment by andyzhangx** [comment]
> Then.. maybe this is blobfuse's job to translate cp, mkdir commands to blob commands?
> When container starts, it will run a bash script like this:
> if [ ! -d "${DIRPRIVATE}html" ]
> then
> mkdir -p "${DIRPRIVATE}html"
> cp -ru "$WWW_PATH/htmlorig"/* "${DIRPRIVATE}html"
> fi

@onepos-zaika I think you could remove above operations first, just mount and make that app in idle state, that could help narrow down the issue, thanks.

**Comment by andyzhangx** [comment]
another way is blobfuse mount manually without this driver:
https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/csi-debug.md#troubleshooting-connection-failure-on-agent-node

and then perform the above operations, and check whether there is list operation.

**Comment by onepos-zaika** [comment]
Actually, I can do some test in the staging cluster.
I still need a way to see how Azure counts the list operation..  otherwise it is very difficult to solve the problem.
The script will not run if the container does not restart. But if we have code update and build a new image, then it will do a deploy rollout restart.  Then $$$ flies away.

**Comment by onepos-zaika** [comment]
Hello! @andyzhangx 
Actually, we did connect to the same storage account with blobfuse in our old server in which we ran similar scripts (not exactly the same). But we discovered this problem only after we have migrated all our sites to AKS.
However, now it looks like this problem may relate to blobfuse more. Should I create another case in blobfuse github and link this one to it?
I shall also send this to the Azure support team so that we can resolve it asap. Thank you.
FYI, we started our migration on 3rd Dec.

![Screenshot 2020-12-08 083657](https://user-images.githubusercontent.com/50311058/101421998-94a53300-3930-11eb-95e0-852ff3799581.jpg)

**Comment by andyzhangx** [comment]
@onepos-zaika I think you could file an support ticket to storage team and also file an issue in blobfuse github.
It's better use blobfuse mount manually to narrow down issue, e.g.
```console
export AZURE_STORAGE_ACCOUNT=
export AZURE_STORAGE_ACCESS_KEY=
blobfuse test --container-name=CONTAINER-NAME --tmp-path=/tmp/blobfuse -o allow_other --file-cache-timeout-in-seconds=120
```

and then run the test.

**Comment by onepos-zaika** [comment]
Finally found a way to open technical support ticket to Azure storage team. The support id is 120120826001226
I shall keep you posted for the finding. Thank you.

**Comment by NaraVen** [comment]
@onepos-zaika, blobfuse does a list after auth but restricts maxResults = 2. Since you have opened a support ticket could you also ask them if this will amount to the same billing as a complete list?  I would be surprised if it does but it woud be eye-opening to know.

**Comment by onepos-zaika** [comment]
Thank you Nara. We actually used blobfuse alone in the old server. The old server is a standalone server in Ubuntu. We did not have this problem in the old server.  This problem only appeared after we moved the server to a AKS cluster. We use Alpine as the container base.

@andyzhangx: may I know how many mount operation will blob-csi-driver do when the a pod is created? Because I have manually created a pvc.. does the mount inside a container mount to a folder in the node or directly to storage account? Thank you.

Even if blobfuse makes 2 lists and fuse do one list on mount, the number of list still not correct. We have a few thousand list operation whenever a pod is created. This is not a small number. Only if every pod did the list recursively can produce such amount of list operations.

My ticket is still not being handled in Azure.  I shall try the mount options your suggested.

below is the current pv and pvc spec:
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: resourcefolderpublic-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # "Delete" is not supported in static provisioning
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: uniqe-volumeid-resourcefolderpublic  # make sure this volumeid is unique in the cluster
    volumeAttributes:
      containerName: public
    nodeStageSecretRef:
      name: resourcefolder-secret
      namespace: onlineshop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resourcefolderpublic
  namespace: onlineshop
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: resourcefolderpublic-pv
  storageClassName: ""
---
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: resourcefolderprivate-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # "Delete" is not supported in static provisioning
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: uniqe-volumeid-resourcefolderprivate  # make sure this volumeid is unique in the cluster
    volumeAttributes:
      containerName: private
    nodeStageSecretRef:
      name: resourcefolder-secret
      namespace: onlineshop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resourcefolderprivate
  namespace: onlineshop
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: resourcefolderprivate-pv
  storageClassName: ""
---

**Comment by NaraVen** [comment]
@onepos-zaika from my comment above, "In many distro's though the fuse filesystem which blobfuse is built-on tries to read the mounted directory resulting in the files being listed. I have seen this in Ubuntu. This is what is happening in your case. ". So, it is listing the entire mount dir because for that OS fuse is triggering a readdir ( which lists). you will save some $$ with the extra options I mentioned above but the first time listing will still cost $.

**Comment by andyzhangx** [comment]
@onepos-zaika there is only one blobfuse mount for every PV on one node, you could ssh to the agent node to check. And as @NaraVen suggested, try use following storage account with additional mount options to have a try:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blob
provisioner: blob.csi.azure.com
parameters:
  skuName: Standard_LRS  # available values: Standard_LRS, Premium_LRS, Standard_GRS, Standard_RAGRS
reclaimPolicy: Retain  # if set as "Delete" container would be removed after pvc deletion
volumeBindingMode: Immediate
mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=120
  - use-attr-cache=true
  - -o attr_timeout=120
  - -o entry_timeout=120
  - -o negative_timeout=120
```

**Comment by onepos-zaika** [comment]
@andyzhangx  If there is only one mount in one node, it won't generate such amount of list....
Because I need to specify the storage account name, how can I do this with StorageClass?.  I did this in pvc...  Thank you.

**Comment by andyzhangx** [comment]
@onepos-zaika in your PV there is also `mountOptions` setting, set as either in PV or storage class:
```
mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=120
  - --use-attr-cache=true
  - -o attr_timeout=120
  - -o entry_timeout=120
  - -o negative_timeout=120
```

**Comment by onepos-zaika** [comment]
Oh..  I understand what you mean now. when the node mounts the storage account, it list recursive. And a container mounts the folder in the node, it also do recursive list... Then this can generate that amount of list.
Then if cache is there in the node, then even if container do a recursive list, the node has a cache to response to it...  
Am I correct?
But why in the earth only me has this problem?  Everyone who uses blob-csi-driver will face the same problem as me....
Does NFS version have this problem?....  
I have added these options to my pv in staging. And I shall do the test right the way because programmer has just triggered the stainging pipeline.
Do I need to remount? or do I just need to do a kubectl apply -f the_file.yaml?
Thank you.

**Comment by andyzhangx** [comment]
@onepos-zaika you need to change PV setting and remount and NFS is not fuse, it may not have such issue.

**Comment by onepos-zaika** [comment]
Good news, in staging cluster, I have 14 pods = 28 containers. In the last build 10 mins ago, the transaction to storage account has been greatly reduced.
![Screenshot 2020-12-08 193151](https://user-images.githubusercontent.com/50311058/101478880-4faeea00-398c-11eb-9103-4353c58ae084.jpg)

I shall try to restart the pods a few times. If it works, I shall apply the setting to production cluster. 
When NFS becomes GA, we shall try to switch to NFS version.
But does NFS supports CDN connection?

**Comment by onepos-zaika** [comment]
But the reduction does not quite reasonable.  It reduced by 10000 times compared to the last build yesterday.
![Screenshot 2020-12-08 194710](https://user-images.githubusercontent.com/50311058/101480261-6bb38b00-398e-11eb-8c15-0131a714d9ab.jpg)

**Comment by andyzhangx** [comment]
so it's reduced by following mount options?
```
mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=120
  - --use-attr-cache=true
  - -o attr_timeout=120
  - -o entry_timeout=120
  - -o negative_timeout=120
```

**Comment by onepos-zaika** [comment]
@andyzhangx  Yes. seems to be. I am applied this to production. Are we ready to restart the pods? If it does not work, then it costs USD30 to restart once.

> so it's reduced by following mount options?
> 
> ```
> mountOptions:
>   - -o allow_other
>   - --file-cache-timeout-in-seconds=120
>   - --use-attr-cache=true
>   - -o attr_timeout=120
>   - -o entry_timeout=120
>   - -o negative_timeout=120
> ```

**Comment by andyzhangx** [comment]
@onepos-zaika quite expensive restart, I think we should add this mountOptions in the example

**Comment by onepos-zaika** [comment]
@andyzhangx  Yes, it does.  I was scared when I checked the cost last week. Anyway, I have tried to restart 3 pods. The first one, it consumed 5k calls. And the other 2 pods only used less than 300 calls to storage account.
We shall release the new build to production tomorrow and expect to have 400 x 300 = 120000 calls which is acceptable and costs around 0.5 USD.
Thank you both @andyzhangx  @NaraVen . An engineer has just picked up my support case in Azure...   I shall keep you posted after tomorrow build.

**Comment by andyzhangx** [comment]
shall we add following mount options by default in this driver to prevent large amount of storage account list operations? @NaraVen 

```
mountOptions:
  - --use-attr-cache=true
  - -o attr_timeout=120
  - -o entry_timeout=120
  - -o negative_timeout=120
```

**Comment by NaraVen** [comment]
Yes, I think it is a very good idea.

**Comment by onepos-zaika** [comment]
@andyzhangx  and  @NaraVen 
Our staging build failed to pass QA last week so we are going to build to prod today. 
However, when I check the storage account usage, it seems like everyday it will generate one time high traffic.
![Screenshot 2020-12-15 103242](https://user-images.githubusercontent.com/50311058/102161350-24635800-3ec2-11eb-8505-ac8db689cb1e.jpg)

It looks like these options can reduce the cost of restarting but there are some cost that cannot be reduced...
Hope NFS will be GA sooner. Thank you both.
I am going to build a new version to prod now. Shall share with you the updated graph later.

**Comment by onepos-zaika** [comment]
![Screenshot 2020-12-15 113540](https://user-images.githubusercontent.com/50311058/102167632-c0dd2880-3ec9-11eb-8150-b20cc7690e45.jpg)

Hello! Restart does not cost a lot now. Cheers.

**Comment by onepos-zaika** [comment]
@andyzhangx 
Hello! We have a new build today and the traffic looks normal during the build.

![Screenshot 2020-12-16 113214](https://user-images.githubusercontent.com/50311058/102301764-796e9f00-3f92-11eb-9a8c-e29be1130ea1.png)

But it looks difficult to find an explanation of daily peak. 
I assume the cache is in node level, then when cache expires, it will update the cache by recursively list my storage account which will generate a 5k list traffic. But instead of 5k, the peak is 3M. It means that every single container is doing the list operation recursively without cache.
On the other hand, if the cache is in container level, then every build will refresh the cache then there will be 3M traffic for every build but it is not the case.
Anyway, NFS seems to be the only way to go. I shall try to test it in staging first.
Thank you.

**Comment by NaraVen** [comment]
@onepos-zaika , if you do not need auth NFS is a good alternate. VNet security is the primary way to secure data in NFS.

**Comment by onepos-zaika** [comment]
Thank you Nara.
auth is nice, but it not mandatory because we have full control over the cluster.
The problem of NFS is that we need to create a new storage account and copy the files to the new one. There is no one-click enable NFS function....    But if it is the only way, we definitely need to do it.

**Comment by NaraVen** [comment]
You can only enable NFS in a new account but you can use AZCopy to copy data from this account to the new one. It is quite fast.

**Comment by andyzhangx** [comment]
@onepos-zaika so you are still using v0.10.0, and it still costs a lot more than you expected?

**Comment by onepos-zaika** [comment]
@andyzhangx  Thank you for coming back to the case. 
![Screenshot 2021-01-26 090607](https://user-images.githubusercontent.com/50311058/105786177-8500ad00-5fb7-11eb-983a-c1db29d42a6f.png)

Adding the new options did solved the problem of high traffic during a new build.
However, as you can see, There is still a daily peak at constant time....   And sometimes it goes terribly high. 
We wanted to use nfsv3 but it does not have the preview in our region. so sad.

**Comment by andyzhangx** [comment]
@onepos-zaika what CSI driver version are you using now? We added `NodeGetVolumeStats` in v0.11.0 that may introduce more calls, need to make sure that's not related. Could you provide the logs from one node driver, follow by: https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed

**Comment by onepos-zaika** [comment]
@andyzhangx 
There are 36k rows of these kind of logs:
I0126 01:37:17.296294       1 utils.go:108] GRPC request: {}
I0126 01:37:17.296662       1 utils.go:113] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{}}}]}
I0126 01:37:17.298396       1 utils.go:107] GRPC call: /csi.v1.Node/NodeGetCapabilities
I0126 01:37:17.298404       1 utils.go:108] GRPC request: {}
I0126 01:37:17.298726       1 utils.go:113] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{}}}]}
I0126 01:37:18.860925       1 utils.go:107] GRPC call: /csi.v1.Node/NodeGetCapabilities
I0126 01:37:18.860940       1 utils.go:108] GRPC request: {}
I0126 01:37:18.861348       1 utils.go:113] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{}}}]}
I0126 01:37:18.865782       1 utils.go:107] GRPC call: /csi.v1.Node/NodeGetCapabilities
I0126 01:37:18.865792       1 utils.go:108] GRPC request: {}
I0126 01:37:18.866141       1 utils.go:113] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{}}}]}
I0126 01:37:21.621957       1 utils.go:107] GRPC call: /csi.v1.Node/NodeGetCapabilities
I0126 01:37:21.621974       1 utils.go:108] GRPC request: {}
I0126 01:37:21.622399       1 utils.go:113] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{}}}]}
I0126 01:37:21.624154       1 utils.go:107] GRPC call: /csi.v1.Node/NodeGetCapabilities
I0126 01:37:21.624162       1 utils.go:108] GRPC request: {}
I0126 01:37:21.624481       1 utils.go:113] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{}}}]}
I0126 01:37:23.245055       1 utils.go:107] GRPC call: /csi.v1.Node/NodeGetCapabilities
I0126 01:37:23.245071       1 utils.go:108] GRPC request: {}
I0126 01:37:23.245415       1 utils.go:113] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{}}}]}
I0126 01:37:23.246845       1 utils.go:107] GRPC call: /csi.v1.Node/NodeGetCapabilities
I0126 01:37:23.246853       1 utils.go:108] GRPC request: {}
I0126 01:37:23.247202       1 utils.go:113] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{}}}]}
I0126 01:37:23.391526       1 utils.go:107] GRPC call: /csi.v1.Identity/Probe
I0126 01:37:23.391542       1 utils.go:108] GRPC request: {}
I0126 01:37:23.391888       1 utils.go:113] GRPC response: {"ready":{"value":true}}

And no NodeGetVolumeStats in the log file.
Thank you.

**Comment by andyzhangx** [comment]
@onepos-zaika thanks, then it's not related to `NodeGetVolumeStats`, and we won't print out those logs in next version, that's really too many useless logs.

**Comment by onepos-zaika** [comment]
Finally,  according to MS support team, the detail of the cause is:
1. “mlocation” is a built-in service and is working as a search tool to search file with a given name in a quick manner. It maintains a database with all files’ index.

2. “mlocation” is added under /etc/cron.daily to run on daily basis and it triggers updatedb to scan every directory on the server to rebuild index of files in database in order to get the search result up-to-date.

3. “updatedb” uses updatedb.config file to white list directory path and file system types.

4. The solution we gave is to white list blobfuse file system and exclude the blobfuse mount directory from being scanned by updatedb, as a result it should not trigger list container requests during future schedule job runs.


For those who suffer the same problem, you may try to follow the steps below.
Detail steps:
1. We created a new configmap in the cluster which contains the new configuration about the script.
2. Then we create a DaemonSet with the new configmap which could apply the configuration changes to every node in the cluster.
3. After creating the DaemonSet, we could monitor it for one day and check if the list request will send to Blob container or not.

configmap fiie: (testcm.yaml)
apiVersion: v1
kind: ConfigMap
metadata:
  name: testcm
data:
  updatedb.conf: |
    PRUNE_BIND_MOUNTS="yes"
    PRUNEPATHS="/tmp /var/spool /media /var/lib/os-prober /var/lib/ceph /home/.ecryptfs /var/lib/schroot /mnt /var/lib/kubelet"
    PRUNEFS="NFS nfs nfs4 rpc_pipefs afs binfmt_misc proc smbfs autofs iso9660 ncpfs coda devpts ftpfs devfs devtmpfs fuse.mfs shfs sysfs cifs lustre tmpfs usbfs udf fuse.glusterfs fuse.sshfs curlftpfs ceph fuse.ceph fuse.rozofs ecryptfs fusesmb fuse blobfuse"

DaemonSet file: (testcmds.yaml)
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: testcmds
  labels:
    test: testcmds
spec:
  selector:
    matchLabels:
      name: testcmds
  template:
    metadata:
      labels:
        name: testcmds
    spec:
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"        
      containers:
      - name: mypod
        image: debian
        volumeMounts:
        - name: updatedbconf
          mountPath: "/tmp"
        - name: source
          mountPath: "/etc"
        command: ["/bin/bash","-c","cp /tmp/updatedb.conf /etc/updatedb.conf;while true; do sleep 30; done;"]
      restartPolicy: Always
      volumes:
      - name: updatedbconf
        configMap:
          name: testcm
          items:
          - key: "updatedb.conf"
            path: "updatedb.conf"
      - name: source
        hostPath:
          path: /etc
          type: Directory

**Comment by andyzhangx** [comment]
This issue is fixed by v1.1.0 release on blobfuse 1.3.7, using `cancel-list-on-mount-seconds=60`
https://github.com/kubernetes-sigs/blob-csi-driver/blob/35a5226ba468c0159247cfb69581aa4f2471f298/deploy/example/storageclass-blobfuse.yaml#L15

```
[OPTIONAL] --cancel-list-on-mount-seconds=0 : libFuse implicitly issues a list command on mount resulting into a call to container to retreive list of blobs. User can avoid this call by disabling the list feature for given number of seconds specified in this parameter. Default value is 0 meaning list call is not disabled.
```

**Comment by andyzhangx** [comment]
`--cancel-list-on-mount-seconds=60` is already set as default in v1.4.0 which could preventhuge storage account list.

**Comment by onepos-zaika** [comment]
Hello! @andyzhangx 
We always have the daemonset in place so we did not notice the problem. However recently, one of the nodes in our cluster refused to run the pod specified by the daemonset for a few days and then high traffic occurred during that days. So I can confirm the daemonset is still required in the current version...

![Screenshot 2021-08-11 111148](https://user-images.githubusercontent.com/50311058/128963824-58728d4d-6444-46e4-b321-b2359c759d90.png)

helm3 list --all-namespaces
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                                             APP VERSION
blob-csi-driver kube-system     1               2021-06-16 11:36:56.1542743 +0800 HKT   deployed        blob-csi-driver-v1.4.0                                            latest


We opened a new case in Azure support for this problem. Thank you.

**Comment by NaraVen** [comment]
Hi @onepos-zaika , you need that config to remove both the mount dir and the temp dir from mlocation scan. @andyzhangx , onepos-zaika had 2 reasons for high billing, the first reason was during mount which your csi driver address in 1.4.0 The second reason is the mlocation service which keeps previously cached files in memory and unnecesarily scans them for safety. This service is a security software mandated by the defender team. The blobfuse mount  and tmp location should be excluded otherwise billing costs will be large during idle time.

**Comment by NaraVen** [comment]
@andyzhangx , It is "mlocate". It should be under /etc/cron.daily

**Comment by andyzhangx** [comment]
> @andyzhangx , It is "mlocate". It should be under /etc/cron.daily

@NaraVen is there a way to change the excluding scanning list in mlocate manually

**Comment by andyzhangx** [comment]
try run this daemonset to remove `/etc/cron.daily/mlocate` which could save storage account list cost:
```console
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/deploy/example/remove-mlocate-ds.yaml
```

**Comment by andyzhangx** [comment]
> try run this daemonset to remove `/etc/cron.daily/mlocate` which could save storage account list cost:
> 
> ```
> kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/147dfd6cc3ce71daaff92dbe11f01905cba48fed/deploy/example/remove-mlocate-ds.yaml
> ```

more graceful way is exclude blobfuse indexing in updatedb config:
```console
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/deploy/example/disable-updatedb-ds.yaml
```
