### ISSUE TITLE
add kubelet path parameter in helm chart installation

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/blob-csi-driver#309]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

could refer to https://github.com/kubernetes-csi/csi-driver-smb/blob/a9a2e47b1790b18e722e9d0b4d413c4e8a520507/charts/latest/csi-driver-smb/values.yaml#L47-L49

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
could you help? @dr0pdb 
thanks

**Comment by dr0pdb** [comment]
sure

/assign
