### ISSUE TITLE
Stop copy pasting code for each helm chart is you already use git tags

### ISSUE THREAD

**Issue by dza89** [kubernetes-sigs/blob-csi-driver#347]

**Comment by andyzhangx** [comment]
can you clarify on this? thanks.

**Comment by dza89** [comment]
The chart repo /folder does not contain just a tgz but also a folder with the code.

**Comment by andyzhangx** [comment]
for an example, both `charts/v1.0.0/blob-csi-driver/*.yaml` and `charts/v1.0.0/blob-csi-driver-v1.0.0.tgz`  files are needed, yaml files are for maintenance, different version could have different file content, and and it's easy to check yaml config on every version in code revew, and tgz file is for helm installation. They are a little redundant while it's necessary.
e.g. if someone only adds one config in tgz file, it's almost impossible to do code review, reviewers have to download that tgz file, and do the `git diff` by themselves, that's really hard way.

**Comment by andyzhangx** [comment]
and we already have tests to make sure tgz file are consistent with yaml configs

**Comment by dza89** [comment]
Yeah, so whenever you need the corresponding code, you do a git checkout <tag>...
Right now you are doing vc in vc.

**Comment by andyzhangx** [comment]
> Yeah, so whenever you need the corresponding code, you do a git checkout < tag >...
> Right now you are doing vc in vc.

keep `charts/latest/blob-csi-driver/*.yaml` in the repo is still necessary for code review

**Comment by dza89** [comment]
I'm just gonna close this issue, as this discussion will have no end.
It just strange to me that an Microsoft 'owned' repository adheres to some really bad practices when it comes to code and git.
