### ISSUE TITLE
Consume Azure blob using serviceprinciple

### ISSUE THREAD

**Issue by doracharan** [kubernetes-sigs/blob-csi-driver#358]
Dear Team, it is working well by using either storage key or SAS token. However, by considering security, is it possible to mount blob using service principle?

**Comment by andyzhangx** [comment]
here is the way to use service principle:
```console
kubectl create secret generic azure-secret --from-literal azurestoragespnclientsecret="xxx" --type=Opaque
```

https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/driver-parameters.md#static-provisioningbring-your-own-storage-container

volumeAttributes.AzureStorageSPNClientID | SPN Client ID |   | No |  
-- | -- | -- | -- | --
volumeAttributes.AzureStorageSPNTenantID | SPN Tenant ID |   | No

but is that more secure?

**Comment by doracharan** [comment]
Thank you for your prompt response @andyzhangx. I have followed the steps, both PV and PVC are created successfully with service principle. But, while deploying the pod is in containercreating and got below events for the pod.

  Warning  FailedMount  6m41s                  kubelet            MountVolume.MountDevice failed for volume "pv-blob-sp" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount  4m23s                  kubelet            Unable to attach or mount volumes: unmounted volumes=[blobsp01], unattached volumes=[default-token-hdmtg blobsp01]: timed outwaiting for the condition
  Warning  FailedMount  2m31s (x9 over 6m41s)  kubelet            MountVolume.MountDevice failed for volume "pv-blob-sp" : rpc error: code = Aborted desc = An operation with the given Volume ID unique-handler already exists

**Comment by andyzhangx** [comment]
`given Volume ID unique-handler already exists` are you create two PVs with same `unique-handler` volumeHandle?

**Comment by doracharan** [comment]
no. volumeHandle is set to unique value.

**Comment by andyzhangx** [comment]
could you try get blob node logs? https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed, thanks.

**Comment by doracharan** [comment]
The below mandatory attribute was missing from pv. after adding it, started working fine.

volumeAttributes.storageAccount 

Thank you @andyzhangx  for your prompt responses on this.

**Comment by doracharan** [comment]
@andyzhangx : Just wanted to confirm, Does Blob Mount works if a storage account and AKS clusters are in two different subscriptions??  I read from one of your comments that "attach an azure disk from another subs is not even supported by azure disk feature". is it the same case with Blob mount??/

**Comment by doracharan** [comment]
PV and PVC are created successfully. while deploying pod it is in creatingcontainer state. while describing the pod it gives "Unable to start blobfuse due to a lack of credentials".

Complete Error: MountVolume.MountDevice failed for volume "test-pv" : rpc error: code = Unknown desc = Mount failed with error: exit status 255, output: Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.

**Comment by andyzhangx** [comment]
> @andyzhangx : Just wanted to check, Does Blob Mount works if a storage account and AKS clusters are in two different subscriptions?? I read from one of your comments that "attach an azure disk from another subs is not even supported by azure disk feature". is it the same case with Blob mount??/

@doracharan it's supported, refer to https://github.com/kubernetes-sigs/blob-csi-driver#option2-bring-your-own-storage-account

**Comment by doracharan** [comment]
@andyzhangx : Thank you for your response. In the above mentioned documnet under Option#1: Use storage class yaml next to   storageAccount it is mentioned that  # cross subscription is not supported.

**Comment by andyzhangx** [comment]
> @andyzhangx : Thank you for your response. In the above mentioned documnet under Option#1: Use storage class yaml next to storageAccount it is mentioned that # cross subscription is not supported.

@doracharan `bring-your-own-storage-account` supports cross subscription and even on-premise

**Comment by doracharan** [comment]
@andyzhangx: it's bit confusing for me. however i have tried with Service principle both PV and PVC are created successfully showing Bound and no events. But, while deploying pod it is in creatingcontainer state. So, described the pod and it says "Unable to start blobfuse due to a lack of credentials".

Complete Error: MountVolume.MountDevice failed for volume "test-pv" : rpc error: code = Unknown desc = Mount failed with error: exit status 255, output: Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.

**Comment by andyzhangx** [comment]
> @andyzhangx: it's bit confusing for me. however, i have tried with Service principle, both PV ,PVC are created successfully and showing Bounded. But, while deploying pod it is in creatingcontainer state. So, described the pod and it says "Unable to start blobfuse due to a lack of credentials".
> 
> Complete Error: MountVolume.MountDevice failed for volume "test-pv" : rpc error: code = Unknown desc = Mount failed with error: exit status 255, output: Unable to start blobfuse due to a lack of credentials. Please check the readme for valid auth setups.

@doracharan are you creating PV by yourself? If you use static provisioning, set up PV/PVC by your own, actually Service principle is not used, anyway, PVC would be in Bound state. May share detailed config.

**Comment by doracharan** [comment]
@andyzhangx: Yes i am creating static PV and then created PVC. 

kubectl create secret generic storageblob-secret --from-literal azurestoragespnclientsecret="xxx" --type=Opaque

persistent volume manifest
===================

apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # "Delete" is not supported in static provisioning
  csi:
    driver: blob.csi.azure.com
    readOnly: true
    volumeHandle: unique-handler  # make sure this volumeid is unique in the cluster
    volumeAttributes:
      storageAccount: ###storageaccntname###
      containerName: ##blobcontainername###
      AzureStorageAuthType: SPN
      AzureStorageSPNClientID: ##SPNAPPID###
      AzureStorageSPNTenantID: ##Tenant###
    nodeStageSecretRef:
      name: storageblob-secret
      namespace: default

persistent volume claim Manifest
=====================

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  volumeName: test-pv
  storageClassName: ""

Sample Deployment manifest
===================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxblob-deployment
spec:
  selector:
    matchLabels:
      app: nginxblob
  replicas: 1
  template:
    metadata:
      labels:
        app: nginxblob
    spec:
      containers:
      - name: nginxblob
        image: nginx:latest
        volumeMounts:
        - name: testblob
          mountPath: "/mnt/blob"
      volumes:
      - name: testblob
        persistentVolumeClaim:
           claimName: test-pvc

**Comment by andyzhangx** [comment]
try set `AzureStorageAuthType: key`, someone else hit the same issue before

**Comment by doracharan** [comment]
Yes. Initial i didn't set this because by default value is Key. Later, once i got the error set AzureStorageAuthType: SPN explicitly.

**Comment by andyzhangx** [comment]
@doracharan so it works now?

**Comment by doracharan** [comment]
@andyzhangx: No, still getting same error.

**Comment by andyzhangx** [comment]
could you get the mount error msg, follow guide here: https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed

This is the working PV config someone else is using:
![image](https://user-images.githubusercontent.com/4178417/119098478-76e40a00-ba48-11eb-8503-596ac695a66c.png)
