### ISSUE TITLE
Support cross subscription storage accounts.

### ISSUE THREAD

**Issue by jabbera** [kubernetes-sigs/blob-csi-driver#371]
**Is your feature request related to a problem?/Why is this needed**
We have a pre-existing adls gen 2 account in a different subscription we would LOVE to mount into our aks jupyterhub cluster. Sadly we cannot easily because cross subscription Storage accounts are not supported. 

**Describe the solution you'd like in detail**
I'd like cross subscription storage accounts to be supported.

**Describe alternatives you've considered**
Crying.

**Comment by andyzhangx** [comment]
I think you could bring your own storage account key, here is an example:

 - store account key as k8s secret
```
kubectl create secret generic azure-secret --from-literal=azurestorageaccountname="xxx" --from-literal azurestorageaccountkey="xxx" --type=Opaque
```
 - set up a storage class with that secret
https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/storageclass-blob-secret.yaml

**Comment by jabbera** [comment]
I'll try but in this example it's explicitly called out as not supported: https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/e2e_usage.md#option1-use-storage-class

**Comment by andyzhangx** [comment]
jus try my provided example: `bring your own storage account key`, it's not documented yet, should work in your scenario

**Comment by jabbera** [comment]
Will do! This is exciting news.

**Comment by jabbera** [comment]
This works but doesn't work with a SasToken or any sort of service principal. This also makes me sad I really only want to give out reader. I can enforce it through mounts but giving out the account key to my entire data lake makes my skin crawl. Do you have any other suggestions aside from enhancing the driver?

**Comment by andyzhangx** [comment]
sastoken should also be supported in cross subscription scenario, try below command to store sastoken instead:
```
kubectl create secret generic azure-secret --from-literal=azurestorageaccountname="xxx" --from-literal azurestorageaccountsastoken="xxx" --type=Opaque
```

while service principal does not work in cross subscription scenario now.

**Comment by jabbera** [comment]
@andyzhangx I tried. It did not work:

Look like getStorageAccount doesn't account for a sastoken param: https://github.com/kubernetes-sigs/blob-csi-driver/blob/05fc802d634e6f5f88073c892a19ab605a2647a3/pkg/blob/blob.go#L440
```
 Warning  ProvisioningFailed    42s (x7 over 105s)  blob.csi.azure.com_aks-generalpool-12857252-vmss000012_4fff9b8c-f2cd-4bc3-937d-40e31d59066f  failed to provision volume with StorageClass "datalake-cleansed": rpc error: code = Unknown desc = failed to GetStorageAccesskey on account() rg(<SNIP>), error: could not find accountkey or azurestorageaccountkey field in secrets(map[azurestorageaccountname:<SNIP> azurestorageaccountsastoken:<SNIP>])
```

**Comment by andyzhangx** [comment]
try with static provisioning example: 
 - https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/driver-parameters.md#static-provisioningbring-your-own-storage-container
 - https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/pv-blobfuse-auth.yaml

**Comment by jabbera** [comment]
This worked! Many thanks.
