### ISSUE TITLE
Chown/chmod have no effect on mounted folders and files

### ISSUE THREAD

**Issue by LouisJULIEN** [kubernetes-sigs/blob-csi-driver#373]
**What happened**:
I installed blob-csi-driver as a replacement of [blobfuse](https://github.com/Azure/kubernetes-volume-drivers/blob/master/flexvolume/blobfuse/README.md) on my kubernetes server. I use it to mount a blob storage container on a [SFTP](https://hub.docker.com/r/emberstack/sftp) pod. The files and folders are mounted correctly inside the pod. I can create/edit/delete them from inside the pod and see the changes in the storage container and vice versa.

**What you expected to happen**:
The permissions can't be changed. The SFTP pod is helpless (no error, no effect) to do so while it could when the volume of the same azure storage container was mounted using blobfuse. I exec into the same SFTP pod and tried to change the access rights using chmod and chown. The command succeeds but it has no effect. The same command works and is effective on other non blob-storage folders/files inside the pod.

**How to reproduce it**:
```
# inside the mounted volume
touch test.txt
ls -la
chown 777 test.txt
ls -la 
```

**Anything else we need to know?**:
The pods running on the node
```
Non-terminated Pods:              (5 in total)
  Namespace                       Name                                            CPU Requests  CPU Limits    Memory Requests  Memory Limits  AGE
  ---------                       ----                                            ------------  ----------    ---------------  -------------  ---
  blob-csi-driver                 csi-blob-node-zjxqv                             30m (1%)      2200m (115%)  60Mi (2%)        2300Mi (106%)  176m
  fluentd-daemonset               fluentd-daemonset-f92p9                         100m (5%)     500m (26%)    300Mi (13%)      1000Mi (46%)   8d
  kube-system                     kube-proxy-4jvm2                                100m (5%)     0 (0%)        0 (0%)           0 (0%)         11d
  monitoring                      monitoring-prometheus-node-exporter-k4f77       10m (0%)      20m (1%)      20Mi (0%)        40Mi (1%)      11d
  sftp-integration-test-louis-ns  sftp-integration-test-louis-79dc9f6d7b-nltwh    0 (0%)        0 (0%)        0 (0%)           0 (0%)         36m
```

The pods in the namespace blob-csi-driver
```
NAME                                  CPU(cores)   MEMORY(bytes)
csi-blob-controller-5c964867b-z7lqc   2m           30Mi
csi-blob-node-zjxqv                   9m           96Mi
```

**Environment**:
- CSI Driver version: v.0.11.0
- Kubernetes version (use `kubectl version`): v1.18.14
- OS (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
- Kernel (e.g. `uname -a`): Linux sftp-integration-test-louis-79dc9f6d7b-nltwh 5.4.0-1040-azure #42~18.04.1-Ubuntu SMP Mon Feb 8 19:05:32 UTC 2021 x86_64 GNU/Linux
- Install tools: argocd
- Others: Azure Cloud cluster

**Comment by andyzhangx** [comment]
related to https://github.com/Azure/azure-storage-fuse/issues/496#issuecomment-704652780

**Comment by LouisJULIEN** [comment]
Thanks you @andyzhangx for your quick answer. It's indeed fuse level setting.
I used the example [here](https://github.com/kubernetes-sigs/blob-csi-driver/blob/7d9775774cbfe191368038f1127219363a012851/deploy/example/storageclass-blobfuse-existing-container.yaml) to add the following mountOptions 
`  - -o allow_other`
Thank you again
