### ISSUE TITLE
add Pod Identity support

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/blob-csi-driver#38]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

add support for [Pod Identity](https://github.com/Azure/aad-pod-identity) to enable finer grain scope of identity as an alternative to using the cluster’s identity.  We do see cases where Azure resources are closely associated with the cluster.  But we also see customers partitioning AKS clusters using namespaces, and in those cases it’s more likely that RBAC grants to resources like storage/key vault would be to Managed Identities that were scoped to a Kubernetes namespace. 

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
marked as long-term since in current stage, we don't want to depend on AAD pod identity component which also depends on cluster identity

**Comment by ThisIsNotTheUserYouAreLookingFor** [comment]
@andyzhangx any chance this is still somewhere on the roadmap? From a security perspective this seems the way to go for our company, as the alternative is mounting the blob storage through fuse to do fine grained authorization. Doing this requires some privileges that we can limit but this feels like a bypass we could avoid with pod identity.

**Comment by andyzhangx** [comment]
cc @bcho

**Comment by bcho** [comment]
/assign @bcho 

Ack, I will look into this later. On the other hand, we are working on a v2 version of pod identity which will be public preview soon, therefore we might have some changes here.

**Comment by bcho** [comment]
> @bcho Any update on this topic? We have this demand for all of our productive AKS clusters as we are seperating our teams with the help of namespaces. Additionally the Key Vault CSI Driver allows the usage of AAD Pod identities.

Hi @mkemmerz we are still working on the workload identity feature integration. In the future, both blob csi and key vault csi driver will support workload identity.

**Comment by miwithro** [comment]
@andyzhangx Pod Identity is being deprecated for https://github.com/Azure/azure-workload-identity

**Comment by andyzhangx** [comment]
supported by https://github.com/kubernetes-sigs/blob-csi-driver/pull/924
