### ISSUE TITLE
Blobfuse loses connection on 1.20.x

### ISSUE THREAD

**Issue by rhummelmose** [kubernetes-sigs/blob-csi-driver#388]
**What happened**:
I upgraded my cluster to 1.20.5. After ~10 minutes the blob mounts are no longer connected and a node reboot or similar is required to remount. After ~10 more minutes the problem repeats itself
I tested also with 1.20.2 and observed the same problem.
I tested with 1.19.9 and it does NOT have the problem.

**What you expected to happen**:
That it stays connected.

**How to reproduce it**:
Spin up a 1.20.5 nodepool (AKS), create a few pods that mount blob volumes and use them (not heavily but consistently). Observe it fail.

**Anything else we need to know?**:
@andyzhangx has more info

**Environment**:
- CSI Driver version: 1.0.0
- Kubernetes version (use `kubectl version`): 1.20.5
- OS (e.g. from /etc/os-release): 18.04.5 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): 5.4.0-1043-azure
- Install tools: AKS
- Others: Nothing fancy

**Comment by rhummelmose** [comment]
Update: Also happens on 1.19.9. Now I've moved to a new cluster, waiting to see whether that resolves the problem.

**Comment by rhummelmose** [comment]
Update: Nothing seems to be going wrong on a new cluster. Question arises, what can cause this issue?

**Comment by rhummelmose** [comment]
No issue observed now on a new cluster after a week.

**Comment by boddumanohar** [comment]
Hi @rhummelmose, were you blobfuse-proxy or the normal driver based mount?

**Comment by andyzhangx** [comment]
they are not using blobfuse-proxy, this issue is more like blobfuse issue itself

**Comment by rhummelmose** [comment]
Yes as @andyzhangx stated, no proxy

**Comment by ErikLundJensen** [comment]
Has blob-csi-driver/blob-csi-driver v1.3.0 been tested at AKS 1.20.5 ?

The [pvc-blob-csi example](https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/pvc-blob-csi.yaml) works as expected, however, using an existing storageaccount in the [pv-blobfuse-csi example](https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/pv-blobfuse-csi.yaml) does not work. The pod is waiting for the mount point to become ready. Both the pv and pvc are bound.

I have run through all the tests at the [csi debug](https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/csi-debug.md) with no errors.
The only concern was that at the agent node the version of blobfuse is very old, however, I don't know if that binary actually is used as the csi-blob-node image contains the new version.

**Comment by andyzhangx** [comment]
> Has blob-csi-driver/blob-csi-driver v1.3.0 been tested at AKS 1.20.5 ?
> 
> The [pvc-blob-csi example](https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/pvc-blob-csi.yaml) works as expected, however, using an existing storageaccount in the [pv-blobfuse-csi example](https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/pv-blobfuse-csi.yaml) does not work. The pod is waiting for the mount point to become ready. Both the pv and pvc are bound.
> 
> I have run through all the tests at the [csi debug](https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/csi-debug.md) with no errors.
> The only concern was that at the agent node the version of blobfuse is very old, however, I don't know if that binary actually is used as the csi-blob-node image contains the new version.

@ErikLundJensen there is e2e test on 1.20.x, could you provide more details about why it does not work, e.g. your app pod events, and also provide agent node driver logs by https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed, there should be `/NodeStageVolume` logs if there is mount error. thanks.

**Comment by andyzhangx** [comment]
> Has blob-csi-driver/blob-csi-driver v1.3.0 been tested at AKS 1.20.5 ?
> 
> The [pvc-blob-csi example](https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/pvc-blob-csi.yaml) works as expected, however, using an existing storageaccount in the [pv-blobfuse-csi example](https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/pv-blobfuse-csi.yaml) does not work. The pod is waiting for the mount point to become ready. Both the pv and pvc are bound.
> 
> I have run through all the tests at the [csi debug](https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/csi-debug.md) with no errors.
> The only concern was that at the agent node the version of blobfuse is very old, however, I don't know if that binary actually is used as the csi-blob-node image contains the new version.

@ErikLundJensen you can also try inline volume directly, that's a little easier to configure: https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/e2e_usage.md#option3-inline-volume

**Comment by ErikLundJensen** [comment]
The inline requires root privileges in the pod.
I have executed the e2e-test toward a 1.21-preview cluster and the yaml-driven testcases went fine as seen below.
However, the go-driven failed due to misconfiguration of AZURE_CLIENT_ID and AZURE_CLIENT_SECRET as my cluster is setup with MSI. I'll may have to run a new test towards a cluster without MSI.

Below is a list of the test that succeeded, non of the tests cover existing storage accounts. I have to get the go-driven testcases running to get that covered.
```
2021/06/16 13:41:42 create example deployments
begin to create deployment examples ...
storageclass.storage.k8s.io/blob created
storageclass.storage.k8s.io/blob-nfs created
persistentvolumeclaim/pvc-blob created
deployment.apps/deployment-blob created
statefulset.apps/statefulset-blob created
statefulset.apps/statefulset-blob-nonroot created
persistentvolumeclaim/pvc-blob-nfs created
deployment.apps/deployment-blob-nfs created
statefulset.apps/statefulset-blob-nfs created
statefulset.apps/statefulset-blob-nonroot-nfs created
sleep 90s ...
No resources found in default namespace.
```

**Comment by andyzhangx** [comment]
have you tried `mountOptions` in latest `v1.3.0` version?
```
        volumeAttributes:
          containerName: EXISTING_CONTAINER_NAME  # required
          secretName: azure-secret  # required
          mountOptions: "-o allow_other --file-cache-timeout-in-seconds=120"  # optional
```

**Comment by ErikLundJensen** [comment]
Specifying the mountOptions in an inline volume specification in a Deployment does not change the folder permissions. It is still 755
```
      - name: blob
        csi:
          driver: blob.csi.azure.com
          readOnly: false          
          volumeAttributes:
            containerName: test
            secretName: azure-blob-secret
            mountOptions: "-o allow_other --file-cache-timeout-in-seconds=120"
```

**Comment by andyzhangx** [comment]
I have tried on my local dev with inline volume on `v1.3.0` version, it works well:
```
# cd /mnt
# ls -lt
total 0
drwxrwxrwx 2 root root 4096 Jun 18 07:23 blobfuse
# cd blobfuse
# echo x > y
# ls -lt
total 28
-rwxrwxrwx 1 root root 22823 Jun 18 07:24 outfile
-rwxrwxrwx 1 root root     2 Jun 18 07:24 y
-rwxrwxrwx 1 root root     2 Jun 18 07:15 b
```

pls run `kubectl edit ds csi-blob-node -n kube-system` to set as `mcr.microsoft.com/k8s/csi/blob-csi:v1.4.0` to make sure latest image is pulled.

**Comment by andyzhangx** [comment]
btw, if mountOptions is not set, the default permission is 0770:
```
# cd /mnt/blobfuse
# ls -lt
total 36
-rwxrwx--- 1 root root 34858 Jun 18 07:31 outfile
-rwxrwx--- 1 root root     2 Jun 18 07:24 y
-rwxrwx--- 1 root root     2 Jun 18 07:15 b
# echo > z
# ls -lt
total 40
-rwxrwx--- 1 root root 35148 Jun 18 07:31 outfile
-rwxrwx--- 1 root root     1 Jun 18 07:31 z
-rwxrwx--- 1 root root     2 Jun 18 07:24 y
-rwxrwx--- 1 root root     2 Jun 18 07:15 b
```

**Comment by andyzhangx** [comment]
pls try with blobfuse-proxy: https://github.com/kubernetes-sigs/blob-csi-driver/tree/master/deploy/blobfuse-proxy, it's now the default setting from v1.6.0, blobfuse-proxy could make blobfuse mount still available after driver restart.
