### ISSUE TITLE
Allow PVC to choose container name.

### ISSUE THREAD

**Issue by stobias123** [kubernetes-sigs/blob-csi-driver#418]
**Is your feature request related to a problem?/Why is this needed**
I'd like to be able to set the container name via the `PersistentVolumeClaim`. `PersistentVolumes` are cluster scoped, and I don't want to delegate access to them to my end users.

**Describe the solution you'd like in detail**
Allow setting the container name from PVC creation.

**Describe alternatives you've considered**
Static provisioning - but I'm getting auth errors when trying to do that.

**Comment by andyzhangx** [comment]
`PersistentVolumeClaim` does not support customized parameter, you can use `PersistentVolume` or storage class to specify `containerName`, they are both cluster scoped

**Comment by stobias123** [comment]
Could this not be accomplished via annotations on the PVC?

Netapp does something similar with their volume driver plugin. 

https://netapp-trident.readthedocs.io/en/stable-v18.07/kubernetes/concepts/objects.html#kubernetes-persistentvolumeclaim-objects

**Comment by andyzhangx** [comment]
pvc annotation can be passed to in-tree driver, while it's not supported by current CSI interface, detailed discussion: https://github.com/kubernetes-csi/external-provisioner/issues/86#issuecomment-465836185

**Comment by stobias123** [comment]
closing per above CSI limitations.

**Comment by progxaker** [comment]
Hello. I was using PVC on IBM using their instructions and could use annotations to select a bucket.
Maybe the CSI interface currently supports this feature?

https://github.com/IBM/ibmcloud-object-storage-plugin#create-a-pvc-and-pod

**Comment by progxaker** [comment]
@stobias123 could you please advise?

**Comment by progxaker** [comment]
Hello @andyzhangx. I was using PVC on IBM using their instructions and could use annotations to select a bucket.
Maybe the CSI interface currently supports this feature?

https://github.com/IBM/ibmcloud-object-storage-plugin#create-a-pvc-and-pod

**Comment by andyzhangx** [comment]
> Hello @andyzhangx. I was using PVC on IBM using their instructions and could use annotations to select a bucket. Maybe the CSI interface currently supports this feature?
> 
> https://github.com/IBM/ibmcloud-object-storage-plugin#create-a-pvc-and-pod

@progxaker IBM driver supports pvc annotation because that's still an in-tree driver (in-tree driver is already deprecated), pvc annotation can be passed to in-tree driver, while it's not supported by current CSI interface, detailed discussion: https://github.com/kubernetes-csi/external-provisioner/issues/86#issuecomment-465836185,

**Comment by progxaker** [comment]
> > Hello @andyzhangx. I was using PVC on IBM using their instructions and could use annotations to select a bucket. Maybe the CSI interface currently supports this feature?
> > https://github.com/IBM/ibmcloud-object-storage-plugin#create-a-pvc-and-pod
> 
> @progxaker IBM driver supports pvc annotation because that's still an in-tree driver (in-tree driver is already deprecated), pvc annotation can be passed to in-tree driver, while it's not supported by current CSI interface, detailed discussion: [kubernetes-csi/external-provisioner#86 (comment)](https://github.com/kubernetes-csi/external-provisioner/issues/86#issuecomment-465836185),

Thank you for the clarification
