### ISSUE TITLE
Deleting a folder can't complete and the command is hung

### ISSUE THREAD

**Issue by goldenpine** [kubernetes-sigs/blob-csi-driver#423]
**What happened**:
After mounting a ADLS gen2 container in a POD on AKS, we create a test/ folder, and touch a file test/dummy.txt. Then run command "rm -r test". The command is hung, and the pod doesn't respond. From Azure Portal, we can see dummy.txt is gone, but the folder test/ is still there.

**What you expected to happen**:
Remove a folder can work promptly.

**How to reproduce it**:

After the driver is installed, below resources are deployed,

`
kind: Secret
apiVersion: v1
metadata:
  name: secret-csi
  namespace: rd-pf-hc
type: "azure-secret"
data:
  accountname: "<STORAGEACCOUNT_NAME>" #base64 encoded
  accountkey: "<STORAGEACCOUNT_PASSWORD>" #base64 encoded

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-csi
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: blob.csi.azure.com #Mandatory, Driver for CSI
    readOnly: false
    volumeHandle: pv-csi #Mandatory
    volumeAttributes:
      storageAccount: testhybrid01
      containerName: customer01
    nodeStageSecretRef:
      namespace: test-hc
      name: secret-csi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-csi
  namespace: test-hc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-csi
  storageClassName: "" #Mandatory

---

kind: Pod
apiVersion: v1
metadata:
  name: pod-nginx-csi
  namespace: test-hc
spec:
  containers:
    - image: roboticdrivehc.azurecr.io/nginx
      name: pod-nginx-csi
      volumeMounts:
        - name: vol-sci
          mountPath: "/mnt/prueba-csi"
  volumes:
    - name: vol-sci
      persistentVolumeClaim:
        claimName: pvc-csi
`

$ kubectl exec -it pod-nginx-csi -n test-hc -- /bin/bash
$ mkdir /mnt/prueba-csi/test
$ rmdir /mnt/prueba-csi/test

Or,
$ touch /mnt/prueba-csi/test/dummy.txt
$ rm -r /mnt/prueba-csi/test

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: latest on master
- Kubernetes version (use `kubectl version`): 1.19.6 (AKS)
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
does `test` dir exist inside pod?

**Comment by goldenpine** [comment]
@andyzhangx thanks for taking a look. The test dir was created on pod under the mounted folder /mnt/prueba-csi by mkdir command. May I know what you mean by saying ' exist inside pod'? 
Also did the below test, on Azure portal, under the blob container, customer01, click 'Add Directory', and create a dir named folderCreatedOnPortal. Then go to the pod again. The newly created folder shows up in the mount folder, but the deletion has the same hung issue. 

$ rm -r  /mnt/prueba-csi/folderCreatedOnPortal

**Comment by andyzhangx** [comment]
The [example](https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/statefulset.yaml) works well, no hung issue:

```console
# k exec -it statefulset-blob-0 sh
# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         124G   18G  107G  15% /
tmpfs            64M     0   64M   0% /dev
tmpfs           3.4G     0  3.4G   0% /sys/fs/cgroup
blobfuse         14G   41M   13G   1% /mnt/blob
/dev/sda1       124G   18G  107G  15% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs           3.4G   12K  3.4G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs           3.4G     0  3.4G   0% /proc/acpi
tmpfs           3.4G     0  3.4G   0% /proc/scsi
tmpfs           3.4G     0  3.4G   0% /sys/firmware
# cd /mnt/blob
# ls -lt
total 8
-rwxrwxrwx 1 root root 1943 May 25 14:18 outfile
drwxrwxrwx 2 root root 4096 May 25 14:18 test
# ls test
hello
# rm -rf test
# ls -lt
total 4
-rwxrwxrwx 1 root root 2523 May 25 14:18 outfile
```

**Comment by SiarheiBortnik** [comment]
We have the same issue. I can not delete folder which are created inside our POD inside mounted folder from Azure Data Lake Gen 2.
We are using AKS 1.20.7 version.
Blob CSI driver version 1.4.0 installed by helm (v1.1.0 works the same).
I can delete files without any problems, but folders could not be deleted by rm command. But in Azure UI I can make all operations. 
Is it any updates regarding this issue?

**Comment by andyzhangx** [comment]
> We have the same issue. I can not delete folder which are created inside our POD inside mounted folder from Azure Data Lake Gen 2.
> We are using AKS 1.20.7 version.
> Blob CSI driver version 1.4.0 installed by helm (v1.1.0 works the same).
> I can delete files without any problems, but folders could not be deleted by rm command. But in Azure UI I can make all operations.
> Is it any updates regarding this issue?

@SiarheiBortnik  could you use the example [here](https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/statefulset.yaml), and then use steps [here](https://github.com/kubernetes-sigs/blob-csi-driver/issues/423#issuecomment-847911511), paste the testing result. I am not sure whether it's related to Azure Data Lake Gen 2 account.

**Comment by andyzhangx** [comment]
I see what happened, should add `--use-adls=true` option for adls gen 2 account(`Hierarchical namespace` enabled), details: https://github.com/Azure/azure-storage-fuse/issues/524#issuecomment-728759718

- example
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blob
provisioner: blob.csi.azure.com
parameters:
  skuName: Standard_LRS  # available values: Standard_LRS, Premium_LRS, Standard_GRS, Standard_RAGRS
  storageAccount: andygen
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=120
  - --use-attr-cache=true
  - --cancel-list-on-mount-seconds=60  # prevent billing charges on mounting
  - -o attr_timeout=120
  - -o entry_timeout=120
  - -o negative_timeout=120
  - --use-adls=true
```

**Comment by SiarheiBortnik** [comment]
> I see what happened, should add `--use-adls=true` option for adls gen 2 account(`Hierarchical namespace` enabled), details: [Azure/azure-storage-fuse#524 (comment)](https://github.com/Azure/azure-storage-fuse/issues/524#issuecomment-728759718)
> 
> * example
> 
> ```yaml
> apiVersion: storage.k8s.io/v1
> kind: StorageClass
> metadata:
>   name: blob
> provisioner: blob.csi.azure.com
> parameters:
>   skuName: Standard_LRS  # available values: Standard_LRS, Premium_LRS, Standard_GRS, Standard_RAGRS
>   storageAccount: andygen
> reclaimPolicy: Delete
> volumeBindingMode: Immediate
> mountOptions:
>   - -o allow_other
>   - --file-cache-timeout-in-seconds=120
>   - --use-attr-cache=true
>   - --cancel-list-on-mount-seconds=60  # prevent billing charges on mounting
>   - -o attr_timeout=120
>   - -o entry_timeout=120
>   - -o negative_timeout=120
>   - --use-adls=true
> ```

Your advice helped me,  with - --use-adls=true in storageclass removing procedure works without any problems. Thank you 
Andy Zhang!
