### ISSUE TITLE
Azure Blob NFS - storage account logs errors

### ISSUE THREAD

**Issue by beaverdevtools** [kubernetes-sigs/blob-csi-driver#448]
Hello,

I successfully mounted a NFS Blob PV/PVC on my AKS Cluster's containers.
My app uploaded many files to the storage and it works great.

Then I checked the storrage account logs, and noticed 80k+ error logs related to the **nfs3lookup** action during my app's import period.
![image](https://user-images.githubusercontent.com/54035020/120278924-25dcdd00-c2b6-11eb-9a74-b2f52cdd7462.png)

Do I missed a mount option ? 
My StorageClass, PV and PVC configuration are as simple as they can be. 
Is this a known bug ?
Can I do something about it ?
I Can't understand, this error means NFS can't find files in storage but the container is working normally.

Thanks,

**Comment by andyzhangx** [comment]
quote from blob nfs team:
```
These would mostly be the normal LOOKUP failure before creating a new file. A normal NFS client doing file create (say file.txt) results in the following seq:

LOOKUP (file.txt) request
LOOKUP response NFS3ERR_NOENT
CREATE (file.txt)
CREATE response success

I acknowledge that it’s not good to show these as client operation errors, but these have been particularly nasty to mask since they can very well be actual errors when user tries to open a non-existent file.

```

**Comment by beaverdevtools** [comment]
Thanks ! Mystery solved.
