### ISSUE TITLE
Windows container support for blob-csi-driver

### ISSUE THREAD

**Issue by yanrez** [kubernetes-sigs/blob-csi-driver#473]
Is there a plan to enable volume mounting of azure blob storage for Windows-based nodes?
Going through the documentation and implementation, it seems to be Linux only.

**Comment by andyzhangx** [comment]
there is no plan to support windows for this driver since this driver is based on blobfuse and NFSv3 client, neither of them supports windows.

**Comment by yanrez** [comment]
My understanding was that windows client supports NFS, although I see azure blob docs refer to Linux support for some reason.
Can you elaborate on NFSv3 gap if possible - is it lack of some specific feature?
Here is public article describing mounting blob on Windows using NFS
https://www.wintellect.com/using-nfs-with-azure-blob-storage/

**Comment by andyzhangx** [comment]
there are some work to do in k8s https://github.com/kubernetes-csi/csi-proxy to support NFSv3 on Windows.
cc @jingxu97
