### ISSUE TITLE
CSI blob node CrashLoopBackOff

### ISSUE THREAD

**Issue by cornel-masson** [kubernetes-sigs/blob-csi-driver#491]
**What happened**:

After install, I see two controller pods, one running, another pending, and the node pod stuck in CrashLoopBackoff. Logs attached.

**What you expected to happen**:

I was expecting one controller and one node pod, both Running, with no errors in the logs.

**How to reproduce it**:

I followed the instructions for [install latest version](https://github.com/kubernetes-sigs/blob-csi-driver/tree/master/charts#install-latest-version). After the helm install, I see the following pods in namespace "kube-system":

```
NAME                                  READY   STATUS             RESTARTS   AGE
kube-proxy-wnnkt                      1/1     Running            4          10d
konnectivity-agent-mrmjh              1/1     Running            3          5d
metrics-server-59d8698d9-qgbhf        1/1     Running            4          10d
coredns-5ccbdcc4c4-82rpq              1/1     Running            4          10d
kube-router-nlv2n                     1/1     Running            4          10d
csi-blob-controller-999db7fb7-2qdbg   0/4     Pending            0          27m
csi-blob-controller-999db7fb7-lshn9   4/4     Running            0          27m
csi-blob-node-49nxt                   2/3     CrashLoopBackOff   13         27m
```

**Logs**
- csi-blob-controller-999db7fb7-2qdbg _(Pending)_: **No logs**
- csi-blob-controller-999db7fb7-lshn9 _(Running)_: [csi-blob-controller.log](https://github.com/kubernetes-sigs/blob-csi-driver/files/6997942/csi-blob-controller.log)
- csi-blob-node-49nxt _(CrashLoopBackOff)_: [csi-blob-node.log](https://github.com/kubernetes-sigs/blob-csi-driver/files/6997941/csi-blob-node.log)

**Events**
- Events for namespace "kube-system": [kube-system-events.log](https://github.com/kubernetes-sigs/blob-csi-driver/files/6997937/kube-system-events.log)

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: **blob-csi-driver-v1.5.0  latest**
- Kubernetes version (use `kubectl version`): **k0s client: v1.20.2, server: v1.21.3+k0s**
- OS (e.g. from /etc/os-release): **Ubuntu 18.04.5 LTS (Bionic Beaver)**
- Kernel (e.g. `uname -a`): **4.15.0-153-generic 160-Ubuntu SMP**
- Install tools: **helm v3.6.3**
- Others: **I'm using k0s on single node (controller+worker)**

**Comment by andyzhangx** [comment]
can you `kubectl describe po csi-blob-node-49nxt -n kube-system`?

**Comment by cornel-masson** [comment]
[describe-csi-blob-node.txt](https://github.com/kubernetes-sigs/blob-csi-driver/files/6998016/describe-csi-blob-node.txt)

**Comment by andyzhangx** [comment]
```
Warning  Unhealthy  46m (x1223 over 21h)  kubelet  (combined from similar events): Liveness probe failed: F0817 07:02:15.720891      24 main.go:157] Kubelet plugin registration hasn't succeeded yet, file=/var/lib/kubelet/plugins/blob.csi.azure.com/registration doesn't exist
```

where is your kubelet path? this driver depends on `/var/lib/kubelet/` kubelet dir.

**Comment by andyzhangx** [comment]
you could configure `--set linux.kubelet=xx` in helm chart to specify another kubelet path

**Comment by cornel-masson** [comment]
kubelet directory:
`drwx------  5 root      root      4096 Aug 16 10:07 kubelet`
```

root@s3a-deploy-test-3:/var/lib/kubelet# **find**
.
./device-plugins
./device-plugins/DEPRECATION
./device-plugins/kubelet.sock
./plugins_registry
./plugins
./plugins/blob.csi.azure.com
./plugins/blob.csi.azure.com/csi.sock


```

**Comment by andyzhangx** [comment]
would you try `v1.4.0` instead?

**Comment by cornel-masson** [comment]
OK, progress! With v1.4.0 the node pod works, but I'm still seeing a 2nd controller pod Pending, with events as follows:

`Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  2m35s  default-scheduler  0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports.`

BTW: why are there **2** controller pods?

**Comment by andyzhangx** [comment]
> OK, progress! With v1.4.0 the node pod works, but I'm still seeing a 2nd controller pod Pending, with events as follows:
> 
> `Warning FailedScheduling 2m35s default-scheduler 0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports.`
> 
> BTW: why are there **2** controller pods?

that's expected since you only have one node, once you have more nodes, those pods would be in Running state
