### ISSUE TITLE
PersistentVolumeClaim: azure: base storage service url required

### ISSUE THREAD

**Issue by cornel-masson** [kubernetes-sigs/blob-csi-driver#493]
**What happened**:
My PersistentVolumeClaim for the blob storage class reports error: "Unknown desc = azure: base storage service url required" on startup.

**What you expected to happen**:
Mount blobfuse correctly to Azure storage account.

**How to reproduce it**:
- Install CSI driver.
- Set k8s default namespace to my app: s3analytics
- Create Azure storage account secret "**azure-secret-csi**": 
  - `kubectl create secret generic azure-secret-csi --from-literal azurestorageaccountname=s3analyticsimages --from-literal azurestorageaccountkey="VALID ACCOUNT KEY HERE" --type=Opaque`
- Create YAML templates for a blob.csi.azure.com storage class & corresponding pvc. Storage class references "azure-secret-csi" by name:
  - [storage-class.yaml](https://github.com/kubernetes-sigs/blob-csi-driver/files/6999802/storage-class.yaml.txt)
  - [pvc.yaml](https://github.com/kubernetes-sigs/blob-csi-driver/files/6999808/pvc.yaml.txt)
- Edit a deployment.yaml to reference the pvc (on mountPath /images):
  - [deployment-image-server-csi-blob.yaml](https://github.com/kubernetes-sigs/blob-csi-driver/files/6999851/deployment-image-server-csi-blob.yaml.txt)
- Do helm release.
- Describe pvc pod shows error event: [describe-pvc.txt](https://github.com/kubernetes-sigs/blob-csi-driver/files/6999813/describe-pvc.txt)

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: **v1.4.0**
- Kubernetes version (use `kubectl version`): **k0s client: v1.20.2, server: v1.21.3+k0s**
- OS (e.g. from /etc/os-release): **Ubuntu 18.04.5 LTS (Bionic Beaver)**
- Kernel (e.g. `uname -a`): **4.15.0-153-generic 160-Ubuntu SMP**
- Install tools: **helm v3.6.3**
- Others: **k0s**

**Comment by andyzhangx** [comment]
pls follow this guide to provide azure credentials first: https://github.com/kubernetes-sigs/blob-csi-driver#prerequisites, otherwise it cannot provision any azure resource.

**Comment by cornel-masson** [comment]
> can you `kubectl describe po csi-blob-node-49nxt -n kube-system`?

I followed:
- [Option2: Bring your own storage account](https://github.com/kubernetes-sigs/blob-csi-driver#option2-bring-your-own-storage-account), then...
- Dynamic Provisioning: again [Option2: Bring your own storage account](https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/e2e_usage.md#option2-bring-your-own-storage-account)...
- which led to me creating the secret as descibed in my original post. The secret only contains the storage account name and key, but it seems the CSI driver is expecting a "base storage service url" as well?

**Comment by andyzhangx** [comment]
you still need to define a basic cloud config file with `/etc/kubernetes/azure.json` on the node, and then restart controller and node, e.g.
```

{
    "cloud":"AzurePublicCloud",
    "tenantId": "xxxx-xxxx-xxxx-xxxx-xxxx",
    "subscriptionId": "xxxx-xxxx-xxxx-xxxx-xxxx",
    "resourceGroup": "resource-group-name",
    "location": "eastus2"
}
```

**Comment by andyzhangx** [comment]
this issue was fixed on master branch now, you don't need to specify the above cloud config file any more.

**Comment by cornel-masson** [comment]
> this issue was fixed on master branch now, you don't need to specify the above cloud config file any more.

I assume this will only be available in the next release? I had to downgrade from v1.5 to v1.4 (see https://github.com/kubernetes-sigs/blob-csi-driver/issues/491#issuecomment-900112728), so would the next release re-introduce the issue I had with v1.5?

**Comment by andyzhangx** [comment]
no, both issues were resolved on mater branch

**Comment by cornel-masson** [comment]
I get further with the new azure.json file, but now my pod reports this error from 'kubelet':

`MountVolume.MountDevice failed for volume "pvc-7e2ebda1-ba2a-4129-9a12-9daf1a520fa8" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name blob.csi.azure.com not found in the list of registered CSI drivers`

The driver (v1.4) is installed, though. Here is the output from `kubectl get csidriver`:
`NAME                 ATTACHREQUIRED   PODINFOONMOUNT   STORAGECAPACITY   TOKENREQUESTS   REQUIRESREPUBLISH   MODES                  AGE
blob.csi.azure.com   false            true             false             <unset>         false               Persistent,Ephemeral   19m`

Here is the [log from the csi-blob-node pod](https://github.com/kubernetes-sigs/blob-csi-driver/files/7005616/blob-node-log.txt)

**Comment by andyzhangx** [comment]
that means your driver did not register with kubelet successfully.

**Comment by cornel-masson** [comment]
Both the csidriver and daemonset is there. See csidriver in previous comment, daemonsets here:

![daemonset](https://user-images.githubusercontent.com/924819/129867311-012ea507-7908-46df-8010-1a6aba10ec86.png)

Is there anything else I can check?

**Comment by andyzhangx** [comment]
sth. wrong with node-driver-registrar, register with path `/var/lib/kubelet/plugins_registry/`
https://github.com/kubernetes-csi/node-driver-registrar#required-permissions

**Comment by cornel-masson** [comment]
I have `sudo chmod 777 /var/lib/kubelet/plugins_registry/`. The socket `blob.csi.azure.com-reg.sock` should now have full read, write and execute permissions. Still no difference.

**Comment by cornel-masson** [comment]
Reminder: I have **two** _controller_ pods, one which is running fine, but the other is still Pending with error:

**1 node(s) didn't have free ports for the requested pod ports**

Why are there two controller pods, and is it a problem that one is stuck without a free port?

**Comment by andyzhangx** [comment]
> Reminder: I have **two** _controller_ pods, one which is running fine, but the other is still Pending with error:
> 
> `1 node(s) didn't have free ports for the requested pod ports`
> 
> Why are there two controller pods, and is it a problem that one is stuck without a free port?

one controller already functions, two controller pods are for redundancy.
