### ISSUE TITLE
[feature request]implement blobfuse-proxy RedHat daemonset

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/blob-csi-driver#546]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

Current blobfuse-proxy.yaml could only be applied to debian based agent nodes, need to implement blobfuse-proxy daemonset for RedHat: https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/blobfuse-proxy.yaml

**Describe alternatives you've considered**

About how to create an OpenShift cluster: https://docs.microsoft.com/en-us/azure/openshift/quickstart-portal

**Additional context**

cc @cvvz

**Comment by andyzhangx** [comment]
also need to check whether it's possible to add a github action to test RPM package install on RedHat, follow: https://github.com/redhat-actions

further more, how to add e2e test coverage on OpenShift, that's also need by other Azure CSI drivers.

**Comment by cvvz** [comment]
The default operating system of OpenShift cluster machines is [Red Hat Enterprise Linux CoreOS (RHCOS)](https://docs.openshift.com/container-platform/4.8/architecture/architecture-rhcos.html), which is not using `yum` to manage RPM software packages. We should find a way to package and  install `blobfuse` and `blobfuse-proxy` in CoreOS Linux. 
cc @andyzhangx
