### ISSUE TITLE
Helm chart version v1.6.0/latest contain missing value

### ISSUE THREAD

**Issue by yuriy-borysiuk-tw** [kubernetes-sigs/blob-csi-driver#548]
The helm chart version: v1.6.0 and  latest contains missing base repo value {{.Values.image.base Repo}}` in file `blobfuse-proxy.yaml`. 

Also in the `values.yaml` file, the value for the `image.blob.tag` is "latest", but there should probably be a specific version. So the image with the `latest` tag is not pulled due to its absence in the repository.

**What happened**:
`Blobfuse-proxy` doesn't want to start due to those issues. 

**What you expected to happen**:

**How to reproduce it**:
https://github.com/kubernetes-sigs/blob-csi-driver/blob/45ec0dd6353c5005e97abeb4e118f3629ee153d1/charts/v1.6.0/blob-csi-driver/templates/blobfuse-proxy.yaml#L27
https://github.com/kubernetes-sigs/blob-csi-driver/blob/45ec0dd6353c5005e97abeb4e118f3629ee153d1/charts/v1.6.0/blob-csi-driver/templates/blobfuse-proxy.yaml#L60
https://github.com/kubernetes-sigs/blob-csi-driver/blob/45ec0dd6353c5005e97abeb4e118f3629ee153d1/charts/latest/blob-csi-driver/values.yaml#L5

**Comment by andyzhangx** [comment]
thanks, it's been fixed in v1.6.0, try:
```console
helm repo update
helm install blob-csi-driver blob-csi-driver/blob-csi-driver --set node.enableBlobfuseProxy=true --namespace kube-system --version v1.6.0
```
