### ISSUE TITLE
Pod is running even files are not available yet

### ISSUE THREAD

**Issue by Cogax** [kubernetes-sigs/blob-csi-driver#558]
**What happened**:
We mount our blob storage container via persistent volume. When we create a Pod with the volume mount and execute `ls` immediately after Pod started, it shows no files. After ca. 20 seconds the files are available (show up when running `ls`).

**What you expected to happen**:
Files should be available if pod is started.

**How to reproduce it**:
Mount a blob storage container with around 40 files to a pod.

**Anything else we need to know?**:
Is this by design? `ATTACHREQUIRED` is set to false for blob csi driver..

```bash
NAME                       ATTACHREQUIRED   PODINFOONMOUNT   STORAGECAPACITY   TOKENREQUESTS   REQUIRESREPUBLISH   MODES                  AGE
blob.csi.azure.com         false            true             false             <unset>         false               Persistent,Ephemeral   121d
disk.csi.azure.com         true             false            false             <unset>         false               Persistent             77d
file.csi.azure.com         false            true             false             <unset>         false               Persistent,Ephemeral   77d
secrets-store.csi.k8s.io   false            true             false             <unset>         false               Ephemeral              2d19h
```

**Environment**:
- CSI Driver version: 1.4.0
- Kubernetes version (use `kubectl version`): v1.21.2

**Comment by andyzhangx** [comment]
@Cogax if you use blobfuse mount directly, will those files appear directly without waiting 20s? follow this guide to mount manually on the node: https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/csi-debug.md#troubleshooting-connection-failure-on-agent-node

 @NaraVen do you know any possible issue that would cause such behavior in blobfuse driver?

**Comment by Cogax** [comment]
@andyzhangx 

I get this response immediately 
```bash
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option
no config filedone reading env vars
```

**Comment by NaraVen** [comment]
@Cogax --cancel-list-on-mount-seconds=0 is the mount option you can use to avoid the 20s delay and override the default. Default delay is set to 20s in blo-csi-driver @andyzhangx , could you confirm if csi is setting a default delay?
Regarding the nonempty tmp dir @Cogax please use --empty-dir-check=false while mounting to allow non empty tmp dirs.

**Comment by andyzhangx** [comment]
> @Cogax --cancel-list-on-mount-seconds=0 is the mount option you can use to avoid the 20s delay and override the default. Default delay is set to 20s in blo-csi-driver @andyzhangx , could you confirm if csi is setting a default delay? Regarding the nonempty tmp dir @Cogax please use --empty-dir-check=false while mounting to allow non empty tmp dirs.

@NaraVen thanks! Current default value of `cancel-list-on-mount-seconds` is `60`, what default value should be better?

[OPTIONAL] --cancel-list-on-mount-seconds=0 : A list call to the container is by default issued on mount. Setting this value to a number greater than 10 seconds will cancel this default list call. For containers with a very large number of files setting this to 10 seconds can save $$. Please be cautious to not set it larger than 60 seconds because no list call will work this time elapses.

https://github.com/kubernetes-sigs/blob-csi-driver/blob/e414576e10d55945384b8e9863854bcc044c36eb/deploy/example/storageclass-blobfuse.yaml#L15

**Comment by Cogax** [comment]
@NaraVen @andyzhangx 
I tried with mount option `--cancel-list-on-mount-seconds=0` and it works! Tanks a lot.

I'm wondering why 60 seconds is the default? We use this driver a lot but as it seems we never touched those mounted files within the first 60 seconds. I would expect, if a Pod has a Running state, that volume is mounted. Otherwise, I would expect that the Pod will stay in Creating state until volume is fully mounted.

Btw.: Sorry for the 20s inaccuracy!

**Comment by andyzhangx** [comment]
this PR(https://github.com/kubernetes-sigs/blob-csi-driver/pull/564) changed `--cancel-list-on-mount-seconds=10` and also added `--empty-dir-check=false`
