### ISSUE TITLE
There is no chart v1.6.0, only latest

### ISSUE THREAD

**Issue by satr** [kubernetes-sigs/blob-csi-driver#563]
**Is your feature request related to a problem?/Why is this needed**
Deploying csi-driver and proxy with flux2

**Describe the solution you'd like in detail**
Each chart should exist with own version, not just as `latest`, which is not good practice to use, we guess

**Describe alternatives you've considered**
Add chart folder for version v1.6.0

**Comment by andyzhangx** [comment]
it's already there: https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/charts/v1.6.0/blob-csi-driver/values.yaml, did you try with 
```console
helm repo add blob-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts
helm install blob-csi-driver blob-csi-driver/blob-csi-driver --set node.enableBlobfuseProxy=true --namespace kube-system --version v1.6.0
```

**Comment by satr** [comment]
This is strange - we two, with my colleague, looked at the list of folders, and saw the largest available number 1.5.0.
This 1.6.0 is very different than `latest`, at least what relates to `proxy`:
- In chart [latest blobfuse-proxy.yaml](https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/charts/latest/blob-csi-driver/templates/blobfuse-proxy.yaml) use values, in [1.6.0 blobfuse-proxy.yaml](https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/charts/v1.6.0/blob-csi-driver/templates/blobfuse-proxy.yaml) it is an old file, no values used
- In values [latest](https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/charts/latest/blob-csi-driver/values.yaml) [there are properties](https://github.com/kubernetes-sigs/blob-csi-driver/blob/1c04b459f7e3effd0c1cd6c85a84c880498759b1/charts/latest/blob-csi-driver/values.yaml#L103) for `blobfuseProxy`, used by this chart , in [1.6.0](https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/charts/v1.6.0/blob-csi-driver/values.yaml) there are no (same for branch 1.6.0):
```
  blobfuseProxy:
    installBlobfuse: true
    blobfuseVersion: 1.4.1
    setMaxOpenFileNum: true
    maxOpenFileNum: "9000000"
``` 
Would you recommend to use (1.6.0)[https://github.com/kubernetes-sigs/blob-csi-driver/tree/master/charts/v1.6.0/blob-csi-driver], instead of (latest)[https://github.com/kubernetes-sigs/blob-csi-driver/tree/master/charts/latest]? Because I'm not sure it is safe to use in Flux chart `latest`, which does not correspond to any `fixed` versions and can be gradually changed.

**Comment by andyzhangx** [comment]
`blobfuseVersion: 1.4.1` is [blobfuse driver](https://github.com/Azure/azure-storage-fuse) version, pls always install fixed release version, e.g. `v1.6.0`, and `latest` tag is for experimental testing, just run:
```console
helm repo add blob-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts
helm install blob-csi-driver blob-csi-driver/blob-csi-driver --set node.enableBlobfuseProxy=true --namespace kube-system --version v1.6.0
```

**Comment by satr** [comment]
Thank you
