### ISSUE TITLE
blob flag provided but not defined: -custom-user-agent                                                                                                                         │

### ISSUE THREAD

**Issue by omer2500** [kubernetes-sigs/blob-csi-driver#581]
**What happened**:
When installing the helm chart on a cluster (with almost default settings) the controller and node are crushing because of this error:

<img width="827" alt="image" src="https://user-images.githubusercontent.com/29802207/144720581-d8c5fa9e-d3fb-44c9-94e8-00b3d7897162.png">

**What you expected to happen**:
the chart should work 

**How to reproduce it**:
 install the chart with default values file 

**Anything else we need to know?**:
i searched for this flag on the blobfuse repo and didnt find anything related to that.

im running on aws eks (temporary)

**Environment**:
- CSI Driver version: 1.7.0 (blob fuse 1.4.1)
- Kubernetes version (use `kubectl version`): v1.21.2
- OS (e.g. from /etc/os-release): debian
- Kernel (e.g. `uname -a`):
- Install tools: installed with terraform helm release resource
- Others:

**Comment by andyzhangx** [comment]
did not repro on my env, try `helm repo update`:
```console
helm repo add blob-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts
helm repo update
helm install blob-csi-driver blob-csi-driver/blob-csi-driver --set node.enableBlobfuseProxy=true --namespace kube-system --version v1.7.0
```

if it still failed, pls provide your driver node pod description by `kubectl describe csi-blob-node-xxx -c blob -n kube-system`

**Comment by omer2500** [comment]
@andyzhangx thanks for the quick answer!
i solved it by using the currect values file (i used the latest instead of 1.7.0)
and it fixed the issue!

Thanks anyway :)
