### ISSUE TITLE
Problem with symlinks

### ISSUE THREAD

**Issue by luanjot** [kubernetes-sigs/blob-csi-driver#600]
**What happened**:
symlinks are treated as files when they are in NFS mounted drives, symlinks created in a mounted drive using the driver are treated as files by the blob storages mounted as NFS in the VMs

**What you expected to happen**:
Existing symlinks to appear as symlinks and new symlinks to be stored in the storage account as symlinks

**How to reproduce it**:
Mount a blob storage and create a symlink, e.g.:

```
x@csi-driver-fsgrouppolicy-file-7f9d4976b5-ftvff [/mnt/home/BIO/master/pipeline] folder $ ll a
lrwxrwxrwx 1 500 500 25 Jan  7 15:20 a -> vcflib_9b6d26a549_centos6
```

Open it in a VM with the blob storage mounted as NFS

```
-rw-r----- 1 root root 25 Jan  7 16:20 /softwarecentos6/a
````

You can see that permissions are different and the type of file is different, the content of the file is the value of the symlink

**Anything else we need to know?**:

I just would like to know if this is expected or if it is a bug indeed and I am sorry for bothering you

**Environment**:
- CSI Driver version: v1.7.0
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"10428892c761e8ca8908e71146eea4751feb545b", GitTreeState:"clean", BuildDate:"2021-11-15T08:35:11Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (e.g. from /etc/os-release): CentOS release 6.10 (Final)
- Kernel (e.g. `uname -a`): Linux csi-driver-fsgrouppolicy-file-7f9d4976b5-ftvff 5.4.0-1059-azure #62~18.04.1-Ubuntu SMP Tue Sep 14 17:53:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
symlink works on my Unbutu 18.04 node with this example: https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/statefulset-nfs.yaml

so if works in your nfs mount inside container, I think that's ok. The symlink file would be stored on a blob storage, and it may use different implementation on azure blob storage layer, as long as it works inside pod, I think that's ok.

```console
# kubectl exec -it statefulset-blob-nfs-0 sh
# df -h
Filesystem                                                                                                       Size  Used Avail Use% Mounted on
overlay                                                                                                          124G   24G  101G  20% /
nfsa00dc5b33c6e4885ac90.blob.core.windows.net:/nfsa00dc5b33c6e4885ac90/pvc-c4cbca16-95ab-4d21-b442-40fdb199ac9e  5.0P     0  5.0P   0% /mnt/blob
tmpfs                                                                                                            3.4G     0  3.4G   0% /sys/firmware
# cd /mnt/blob
# ls -lt
# ln -s link outfile
ln: failed to create symbolic link 'outfile': File exists
# ln -s outfile link
# ls -lt
total 29
-rw-r--r-- 1 root root 28840 Jan  9 03:01 outfile
lrwxrwxrwx 1 root root     7 Jan  9 03:01 link -> outfile
```

**Comment by luanjot** [comment]
OK. Yes, indeed, creating a symlink in the pod works, but It is just that it does not work in the same way as the official Azure NFS implementation of blob storage accounts, so, any link created in one technology is not usable in the other.

But if this is not in scope of your libraries, I guess we can close the ticket.

I will find a different solution.

Thank you

**Comment by andyzhangx** [comment]
@luanjot what do you mean `Open it in a VM with the blob storage mounted as NFS`?  the pod nfs access is still based on nfs mount on one VM, you could ssh to agent node, and try `mount | grep nfs`, 

```console
#mount | grep nfs
accountname.blob.core.windows.net:/accountname/pvc-c4cbca16-95ab-4d21-b442-40fdb199ac9e on /var/lib/kubelet/pods/b0852f08-c2b8-49a9-a14a-dfc72b775086/volumes/kubernetes.io~csi/pvc-c4cbca16-95ab-4d21-b442-40fdb199ac9e/mount type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,nolock,proto=tcp,port=2048,timeo=600,retrans=2,sec=sys,mountaddr=52.239.174.228,mountvers=3,mountport=2048,mountproto=tcp,local_lock=all,addr=52.239.174.228)

:/var/lib/kubelet/pods/b0852f08-c2b8-49a9-a14a-dfc72b775086/volumes/kubernetes.io~csi/pvc-c4cbca16-95ab-4d21-b442-40fdb
199ac9e/mount# ls -lt
total 1884
-rw-r--r-- 1 root root 1928151 Jan 10 02:52 outfile
lrwxrwxrwx 1 root root       7 Jan  9 03:01 link -> outfile
```

if you use same mount options, and mount on same nfs file share, I think you could get same content.

**Comment by luanjot** [comment]
Hello,

I did put the same options in the pod, but I am not sure how to verify they are the same because I cannot see them on kubectl describe.

In any case, my behaviour at the moment is that both links are different. This is what I see when I open it from a VM. As you can see, the symlink created in the pod is **not** a symlink and the symlink created in the vm is:

```
.vm /nfs> ll
total 104201
-rw-r----- 1 root    zabbix        17 Jan 10 16:46 file.txt
-rw-r----- 1 root    zabbix         8 Jan 10 16:46 symlink_from_pod.txt
lrwxrwxrwx 1 jgarcia zabbix         8 Jan 10 16:47 symlink_from_vm.txt -> file.txt
```

This is what I see from inside the pod:

```
-rwxrwxrwx 1 sg sophia_dev        17 Jan 10 15:46 file.txt
drwxrwxrwx 2 sg sophia_dev      4096 Jan  1  1970 sg-root
-rwxrwxrwx 1 sg sophia_dev 106699440 Dec 22 09:53 SOPHiA-DDM-v4-4.5.3.1.pkg
lrwxrwxrwx 1 sg sophia_dev         8 Jan 10 15:46 symlink_from_pod.txt -> file.txt
-rwxrwxrwx 1 sg sophia_dev         0 Jan 10 15:47 symlink_from_vm.txt
```

As you can see, it is the other way around.

When I open them in azure, I can also see that they are different on the server side (one has 8 bytes, the other one zero):

![image](https://user-images.githubusercontent.com/1869014/148796267-11768bd9-d7f7-4d3a-9460-f51b0b2fe511.png)

**Comment by luanjot** [comment]
Hello,

I finally figured out the issue. It was that I was indeed not mounting it with the right options as the protocol nfs was not set properly so it was being mounted in a different way.

Now I can see the links from the vm in the right way.

Thank you
