### ISSUE TITLE
MSI authentication: Identity not found issue

### ISSUE THREAD

**Issue by mkemmerz** [kubernetes-sigs/blob-csi-driver#618]
Hello, I am not able to get the authentication to work with my **user-assigned** Managed Identity and Blob Storage. The MSI has permissions on the Storage Account and Container. Service Principal auth worked fine for me.

blob-csi-driver version 1.8.0 is used.

I have tried all authentication parameters as suggested in the example files: `AzureStorageIdentityClientID, AzureStorageIdentityObjectID, AzureStorageIdentityResourceID`. Unfortunately I always receive an error message "Identity not found".

My AKS is located in a different subscription than the Storage Account and MSI - is this maybe the issue?

```
MountVolume.MountDevice failed for volume "azblobvolumemsi" : rpc error: code = Unknown desc = Mount failed with error: rpc 
error: code = Unknown desc = exit status 255 OAUTH Token : Refresh token failed Failed to retrieve OAuth Token from IMDS endpoint (CURLCode: 0, HTTP code: 400): {"error":"invalid_request","error_description":"Identity not found"}
Unable to retrieve OAuth token: Failed to retrieve OAuth Token from IMDS endpoint (CURLCode: 0, HTTP code: 400): 
{"error":"invalid_request","error_description":"Identity not found"} Unable to start blobfuse due to authentication or connectivity issues. 
Please check the readme for valid auth setups. no config filedone reading env varsURI token request URL printed out http://xxx/metadata/identity/oauth2/token?api-version=2018-02-01&mi_res_id=/subscriptions/xxx/resourcegroups/xxx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/xxx&resource=https://storage.azure.com/ 
```

My volume:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azblobvolumemsi
spec:
  storageClassName: azblob
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: unique-volume-id-612349616666172394
    volumeAttributes:
      resourceGroup: xxx
      storageAccount: xxx
      containerName: xxx
      # refer to https://github.com/Azure/azure-storage-fuse#environment-variables
      AzureStorageAuthType: msi  # key, sas, msi, spn
      AzureStorageIdentityResourceID: "xxx"
```

**Comment by andyzhangx** [comment]
could you refer to https://github.com/Azure/azure-storage-fuse#environment-variables, and try using env with blobfuse command to check whether msi works?

**Comment by andyzhangx** [comment]
btw, I think the msi should be aks cluster's kubelet managed identiy.

**Comment by mkemmerz** [comment]
> btw, I think the msi should be aks cluster's kubelet managed identiy.

Thanks a lot for the quick reply! Do you know if it has to be the kubelets identity? 
We are using seperated namespaces for our teams so we basically have the need to be able to use the team's specific managed identity to access the blob.

**Comment by andyzhangx** [comment]
as I know, kubelet managed identiy is bound to the agent node, could you try kubelet identity first? I am not quite sure.

**Comment by mkemmerz** [comment]
> as I know, kubelet managed identiy is bound to the agent node, could you try kubelet identity first? I am not quite sure.

I will definetly try this out. Thanks for the hint.
