### ISSUE TITLE
Upgrading AKS cluster to 1.21.7 facing volume mount issue.

### ISSUE THREAD

**Issue by PrathibaNet** [kubernetes-sigs/blob-csi-driver#637]
Hi ,
In our AKS cluster we have installed csi-secrets-store using helm in terraform as below
resource "helm_release" "csi-secrets-store" {
  name             = "csi-secrets-provider-azure"
  repository       = var.kv_csi_chart_url
  chart            = "csi-secrets-store-provider-azure"
  version          = "0.0.7"
  namespace        = var.kv_csi_namespace
  create_namespace = true
}

variables are as below
variable kv_csi_chart_url {
  default     = "https://azure.github.io/secrets-store-csi-driver-provider-azure/charts"
  description = "Helm chart url for Key Vault CSI"
}
variable kv_csi_namespace {
  default     = "kv-csi"
  description = "Name of the Key Vault CSI namespace"
}

Below is the secret-provider-class, which also we deploy to our AKS cluster 

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: $SECRET_PROVIDER_CLASS
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "$KEYVAULT_NAME"
    tenantId: "$TENANT_ID"
    objects:  |
      array:
        - |
          objectName: ai-main 
          objectType: secret
          objectAlias: AI__InstrumentationKey

Then we deploy our application pod with volume mounts to access our keyvault secrets. The container itself is not creating and we are getting volume mount error. 
![image](https://user-images.githubusercontent.com/89978897/161078512-2dc1ecb9-672f-46c3-9eea-390459ab89ab.png)

With AKS version 1.18.10 this setup was working fine. there we used old csi chart url. Kindly help to resolve this issue

**Comment by crgarcia12** [comment]
Have you consider using the module instead: https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver

```
 "addonProfiles": {
    "azureKeyvaultSecretsProvider": {
      ...,
      "identity": {
        "clientId": "<client-id>",
        ...
      }
    }
```
