### ISSUE TITLE
Extra file is getting created for each folder in storage account

### ISSUE THREAD

**Issue by anjalisajith** [kubernetes-sigs/blob-csi-driver#670]
**What happened**:
I was able to connect Aks back end to azure storage account blob using csi driver. Able to get the files in the blob as well. Issue : for each folder in the storage account and extra empty file with the name same as the folder is getting created.

**What you expected to happen**

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 0.11.0
- Kubernetes version (use `kubectl version`): 1.21.9
- OS (e.g. from /etc/os-release): Linux
- Kernel (e.g. `uname -a`):
- Install tools: csi driver
- Others:

**Comment by anjalisajith** [comment]
Please help me to resolve this issue

**Comment by andyzhangx** [comment]
do you have more details? what's the extra file?

**Comment by andyzhangx** [comment]
any update? the blob csi driver itself won't write any data to the mounted folder since CSI driver only deals with mount/unmount, create/delete volume.

**Comment by anjalisajith** [comment]
Requirement is mounting the AKS  backend to Azure storage account. When we tried to implement this through direct mount to file share (dynamic storage account ) , it is working perfectly without any duplicate files. When we tried to implement the same solution with azure blob as the backend using csi driver (static storage account with secret), we face this duplicate file issue.

**Comment by anjalisajith** [comment]
Attached screenshot shows the error , with duplicate txt file with 0KB size created for each folder. 
![Uploading IMG_20220428_133647~2.jpg…]()

**Comment by anjalisajith** [comment]
![Uploading IMG_20220428_133647~2.jpg…]()

**Comment by andyzhangx** [comment]
the kubelet identity should have write permission on the `Virtual network`. similar to https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/install-driver-on-aks.md, you should assign `Contributor` role on that `Virtual network` using by your cluster.

**Comment by anjalisajith** [comment]
Hi Andy,

I have provided the contributor access to AKS agent pool in the VNET and that particular error git fixed. But now I am getting the similar error for storage account /listkeys/action when trying with the existing storage account

**Comment by anjalisajith** [comment]
Hi Andy,

I have provided the contributor access to AKS agent pool in the VNET and that particular error git fixed. But now I am getting the similar error for storage account /listkeys/action when trying with the existing storage account. Similar to #186 could you please suggest how to fix this ?

Another query:
Is it possible to use this driver setup in non-azure environments.( eg: connecting on premise systems kubernetes clusters to azure blob using csi drivers )

**Comment by andyzhangx** [comment]
@anjalisajith then you need to grant storage account contributor access to the driver identity.
This driver supports non-azure environments

**Comment by anjalisajith** [comment]
Hi Andy,

Thanks for the suggestions and it resolved the access issue. I have another query regarding the version support.

I am getting the below error when trying to install blob csi driver in AKS (version 1.22.6 ) using Terraform ( version > 2.86.0). 

Error : Unable to build kubernetes objects from release manifest: unable to recognise " ": no matches found for kind " CSIDriver" in version. "storage.k8s.io/v1beta1" in resource "helm_release"

The Terraform code is working fine with AKS version 1.20.9.
Could you please let me know if it is some issues with the version support?

**Comment by andyzhangx** [comment]
@anjalisajith I think you are using old version with `v1beta1`, it's now `storage.k8s.io/v1 `
https://github.com/kubernetes-sigs/blob-csi-driver/blob/dd7bc52f6813d63d7a22f6f88160a095d920ee56/deploy/csi-blob-driver.yaml#L2-L3

**Comment by anjalisajith** [comment]
> @anjalisajith I think you are using old version with `v1beta1`, it's now `storage.k8s.io/v1 `
> 
> https://github.com/kubernetes-sigs/blob-csi-driver/blob/dd7bc52f6813d63d7a22f6f88160a095d920ee56/deploy/csi-blob-driver.yaml#L2-L3

Yes it worked!!

**Comment by anjalisajith** [comment]
Question regarding the storage part:

Storage account blob size limit is the size limit set by Microsoft, while deploying the blob csi driver using nfs we can specify the size only for the pvc( eg: 1GiB) . After deployment  in Azure portal a pv will get created automatically  with the same size as the pvc (1GiB). 

My query is if the size exceeds 1 GiB will the pv size grows automatically based on the storage account size OR do we need  to specify the pv size also in the yaml ?

**Comment by andyzhangx** [comment]
> Question regarding the storage part:
> 
> Storage account blob size limit is the size limit set by Microsoft, while deploying the blob csi driver using nfs we can specify the size only for the pvc( eg: 1GiB) . After deployment in Azure portal a pv will get created automatically with the same size as the pvc (1GiB).
> 
> If the size exceeds 1 GiB will the pv size grows automatically based on the storage account size ? Is there any way to specify the pv size also in the yaml instead of getting created with the same size as that of the pvc ?

@anjalisajith if size exceeds 1 GiB, the pv size grows automatically. the pv is actually a directory under one storage account, the capacitary should be 100TB per storage account as I could recall.
