### ISSUE TITLE
csi-blobfuse-proxy stuck in crashbackoffloop

### ISSUE THREAD

**Issue by lw3636** [kubernetes-sigs/blob-csi-driver#673]
What happened:
Control plane csi-blobfuse-proxy pod stuck in crashbackoffloop -

It is experiencing a crashbackoffloop error. When looking at the logs, I see the error 
'+ false == true
+ dpkg -i /tmp/blobfuse-proxy-v0.1.0.deb
dpkg: error: cannot access archive '/tmp/blobfuse-proxy-v0.1.0.deb': No such file or directory'

csi-blobfuse-proxy which is in the kube-system namespace of the cluster.

We tried to scale up nodes to see if this is issue with node, but that did not help. Also, we killed the pods but it again went to CrashLoopBackoff state

Expected Result:
Pod marked as ready

Actual Result: 
Pod stuck in CrashBackoffLoop

[github csi-blogfuse-proxy describe pod.txt](https://github.com/kubernetes-sigs/blob-csi-driver/files/8641916/github.csi-blogfuse-proxy.describe.pod.txt)

**Comment by andyzhangx** [comment]
pls run, original daemonset is on master branch:
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/deploy/v1.11.0/blobfuse-proxy.yaml
```

**Comment by lw3636** [comment]
Perfect, thank you. That seemed to resolve the issue.
