### ISSUE TITLE
blobfuse-proxy pods are not starting while installing using helm 

### ISSUE THREAD

**Issue by juthikashenoy** [kubernetes-sigs/blob-csi-driver#705]
I am installing Blob CSI driver in AKS cluster using this command - 
https://github.com/kubernetes-sigs/blob-csi-driver/tree/master/deploy/blobfuse-proxy#step2-install-blob-csi-driver-with-blobfuse-proxy-enabled
helm install blob-csi-driver blob-csi-driver/blob-csi-driver --namespace kube-system --version v1.14.0 --set node.enableBlobfuseProxy=true

I expect to see the pods like this ( this is from a differnt AKS cluster using the same command ) 
csi-blobfuse-proxy-2ksxj                        1/1     Running   0          39d
csi-blobfuse-proxy-8fswb                        1/1     Running   0          39d
csi-blobfuse-proxy-m95fr                        1/1     Running   0          14d
csi-blobfuse-proxy-ss86p                        1/1     Running   0          8d

Is csi-blobfuse-proxy no loner needed ?
https://github.com/kubernetes-sigs/blob-csi-driver/tree/master/deploy/blobfuse-proxy#enable-blobfuse-proxy-on-existing-blob-csi-driver
this link - kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/deploy/v1.14.0/blobfuse-proxy.yaml doesnt work anymore . 
Please lmk - thanks ! 

**How to reproduce it**: helm install command 

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: chart - blob-csi-driver-v1.15.0 
- Kubernetes version (use `kubectl version`): 1.21.9
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
Linux aks-cobmodelnpl-42922332-vmss000000 5.4.0-1085-azure #90~18.04.1-Ubuntu x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
correct, csi-blobfuse-proxy is no loner needed from v1.14.0, there is a `install-blobfuse-proxy` in initContainer which would do same thing.
