### ISSUE TITLE
Version missmatch between GitHub release and helm chart version

### ISSUE THREAD

**Issue by sphinx02** [kubernetes-sigs/blob-csi-driver#714]
Hi,
following the last 2 releases of the blob-csi-driver I recognized that the chart- and app-version of the helm-chart is always one version higher than the release version of the blob-csi-driver in GitHub.

Currently e.g. if listing the helm-chart versions:
![grafik](https://user-images.githubusercontent.com/10533724/176888975-30e797c5-457e-4e6f-a151-dd23c54f8d8b.png)

And if looking at the GitHub releases page:
![grafik](https://user-images.githubusercontent.com/10533724/176889046-9f7f17e5-3bb7-4843-97f3-90b248fc810c.png)

As far as I understand is e.g. the current helm-chart with chart-version v1.16 matching the GitHub-Release v1.15. That is quite confusing, especially if changelog is of interest.

Is there any chance to keep at least the app-version in sync with the version of the GitHub release version? Even better would be to keep both in sync.

**Comment by sphinx02** [comment]
@andyzhangx but how do I know which helm-chart version contains which GitHub release generally?

**Comment by andyzhangx** [comment]
@sphinx02 I think you could use v1.15.0 helm-chart version, it would have v1.15.0 GitHub release

**Comment by andyzhangx** [comment]
Current v1.16.0 helm-chart actually contains the `latest` GitHub release which is for testing purpose, and when `v1.16.0` is released, it would contain v1.16.0 GitHub release, and now you could try `v1.15.0` which is the latest released version.

we could not set `version` as `latest`(invalid format) in `charts/latest/blob-csi-driver/Chart.yaml`, that's reason we always set as a higher version than latest released version, so user could still install master branch chart for testing purpose:
https://github.com/kubernetes-sigs/blob-csi-driver/blob/e7163d50771c96c3290260ba2faf9c160822b1e8/charts/latest/blob-csi-driver/Chart.yaml#L5

 - right way to install latest released version:
```console
helm repo add blob-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts
helm repo update
helm install blob-csi-driver blob-csi-driver/blob-csi-driver --set node.enableBlobfuseProxy=true --namespace kube-system --version v1.15.0
```

**Comment by sphinx02** [comment]
Sorry, I still dont get it. Does that mean that in this case the helm-chart version v1.15.0 did change over time?

**Comment by andyzhangx** [comment]
> Sorry, I still dont get it. Does that mean that in this case the helm-chart version v1.15.0 did change over time?

@sphinx02 NO, v1.15.0 is released, so it won't change over time, and v1.16.0 is master branch version, it may change in the future.

**Comment by sphinx02** [comment]
I am not sure but I think we had the same thing with v1.15.0, it was latest helm-chart until you recently made the v1.15.0 GitHub release. If you ask me that is completely confusing. I have various clusters running on v1.15.0 helm-chart which was available since more than 2 weeks but since the v1.15.0 GitHub release, the v1.15.0 helm-chart version seem to be something different now.

I recommend to use a different repo for unversioned and untestet latest master-charts like:
`helm repo add blob-csi-driver-master https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver-master/master/charts`
or
`helm repo add blob-csi-driver-beta https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver-beta/master/charts`

I think it is quite confusing and in production environments even dangerous if identical helm-chart version differs over time.

**Comment by andyzhangx** [comment]
@sphinx02 what about add such notes: https://github.com/kubernetes-sigs/blob-csi-driver/pull/715

**Comment by sphinx02** [comment]
To be honest, I dont think that is enough. I am not sure if its only me but if there is an offical helm-repository of a GA helm tool I expect that the latest helm-chart is the latest stable one. Untested master releases should never be the latest release of a GA helm repository.

**Comment by sphinx02** [comment]
@andyzhangx that sounds great. This way the latest release is always the latest stable release and also a versioned release does not change over time (except the special master v0.0.0 release). Thank you again!
