### ISSUE TITLE
mount azure blob cause  blob content-type is all application/octet-stream

### ISSUE THREAD

**Issue by lifejoyforpy** [kubernetes-sigs/blob-csi-driver#743]
Hi ,i  use  aks  mount aure blob .but  i found all files  content-type is  application/octet-stream,this is not i want , i  hope  if file is 
jepg ,this contenttype is  image/jpeg,

**Comment by lifejoyforpy** [comment]
[](url
![1665314a5a94e1ce4c65417ee286cd0](https://user-images.githubusercontent.com/38183800/187056679-b4be1177-c5c5-491b-81cc-61b4f60c5e7c.jpg)
)

**Comment by andyzhangx** [comment]
@lifejoyforpy try set as `--set-content-type=true` in pv mount options.

```
--set-content-type=false : Flag to turn on automatic 'content-type' property based on the file extension. Default is false so content-type will only be set if the uploaded file specifies it.
```

**Comment by lifejoyforpy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lifejoyforpy** [comment]
> -set-content-type=true  it does not works 
this is my pv.yaml
![1661784485798](https://user-images.githubusercontent.com/38183800/187229623-27cbba8c-1b85-490b-a9df-8b9357f13733.png)

**Comment by andyzhangx** [comment]
@vibhansa-msft do you have any insight about this issue? Thanks.

**Comment by lifejoyforpy** [comment]
> @vibhansa-msft do you have any insight about this issue? Thanks.

i redepoy ,now it works . tks

**Comment by andyzhangx** [comment]
thanks for the confirm.
