### ISSUE TITLE
Unable to upgrade blob-csi-driver from 1.13 to 1.16 

### ISSUE THREAD

**Issue by kevball2** [kubernetes-sigs/blob-csi-driver#755]
**What happened**:  Attempting to update driver results in an error during installation 

`curl -skSL https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/v1.16.0/deploy/install-driver.sh | bash -s v1.16.0 blobfuse-proxy --`

> Warning: resource csidrivers/blob.csi.azure.com is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
> The CSIDriver "blob.csi.azure.com" is invalid: spec.volumeLifecycleModes: Invalid value: []storage.VolumeLifecycleMode{"Persistent", "Ephemeral"}: field is immutable

**What you expected to happen**: Expectation is that the driver to update successfully 

**How to reproduce it**: Run the following : 

`curl -skSL https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/v1.16.0/deploy/install-driver.sh | bash -s v1.13.0 blobfuse-proxy --`

**Anything else we need to know?**:  This cluster was created through Azure Machine Learning Studio

**Environment**:

- CSI Driver version:
--  image: mcr.microsoft.com/k8s/csi/blob-csi:v1.4.1
-- image: mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.13.0
- Kubernetes version (use `kubectl version`): v1.23.8
- OS (e.g. from /etc/os-release): AKSUbuntu-1804containerd-2022.07.28
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
there is immutable volumeLifecycleModes config change, you could uninstall this driver and then install driver again, that should fix the issue.

**Comment by robin-wayve** [comment]
will uninstalling cause downtime or lose volumes?

**Comment by andyzhangx** [comment]
> blobfuse-proxy

@robin-wayve uninstall the driver would have downtime since it would also remove the blobfuse-proxy daemonset, the blobfuse volume mounts would be invalid during driver uninstall, while uninstalling driver won't lose volume data, you only need to restart all pods that are using blobfuse volume mounts
