### ISSUE TITLE
Can we choose cool or hot tier in the driver parameters?

### ISSUE THREAD

**Issue by nikawang** [kubernetes-sigs/blob-csi-driver#763]
**Is your feature request related to a problem?/Why is this needed**

Some workloads need to storage data into different tier like hot, cool
**Describe the solution you'd like in detail**

There's an option to choose the data tier
**Describe alternatives you've considered**

**Additional context**

Elastic Search on K8S

**Comment by rainerleber** [comment]
+1

**Comment by andyzhangx** [comment]
there is a https://github.com/kubernetes-sigs/blob-csi-driver/pull/775  to support this feature, pls note that only standard storage account could choose `Hot` or `Cool`, premium account can only use `Premium`
