### ISSUE TITLE
unzip create file  slow

### ISSUE THREAD

**Issue by lifejoyforpy** [kubernetes-sigs/blob-csi-driver#764]
i use azure-blob mount aks pod,     i use c# develope . i unzip  a file in mount folder. i found slowly , 
85mb zip file  unzip blob mount  folder taks 8 s. i
![1664519599341](https://user-images.githubusercontent.com/38183800/193205657-1cda11af-e0c3-419b-94af-cf99708ad7b4.png)

**Comment by lifejoyforpy** [comment]
unzip use linux  files folder ,unzip blob use mount azure blob folder.,  it is very slowly.

**Comment by cvvz** [comment]
Aure you using blobfuse or NFS protocal?

**Comment by lifejoyforpy** [comment]
blobfuse  blobfuse 

> Aure you using blobfuse or NFS protocal?

blobfuse   protocal

**Comment by cvvz** [comment]
Could you please provide the AKS version, region,  blob csi driver version zip/unzip command so that I can reproduce it on my cluster?

Also, please make sure that AKS node region and storageaccount region are the same so that it won't cause too much network latency.

**Comment by lifejoyforpy** [comment]
my aks  version 1.21.9  ,region China East 2 , 
i use c# code  unzip files ,create files
![1664521603156](https://user-images.githubusercontent.com/38183800/193211321-a8f6ad6a-138d-4445-9052-eb8bfc5471ab.jpg)

**Comment by lifejoyforpy** [comment]
i cannot found csi driver version ,i enbale using the microsoft docs https://learn.microsoft.com/en-us/azure/aks/azure-blob-csi?tabs=Blobfuse
![image](https://user-images.githubusercontent.com/38183800/193211665-143fa0cd-273e-4c77-a373-1e2a263961d0.png)
![image](https://user-images.githubusercontent.com/38183800/193211715-2129e98a-403f-4b8b-bc37-1c1b916e9f36.png)

**Comment by lifejoyforpy** [comment]
![image](https://user-images.githubusercontent.com/38183800/193211907-9ca19379-5950-41a9-873b-37a92e884b32.png)
this is my yaml

**Comment by lifejoyforpy** [comment]
i  hope u can help me .thanks

**Comment by lifejoyforpy** [comment]
> Could you please provide the AKS version, region, blob csi driver version, zip/unzip command so that I can reproduce it on my cluster?
> 
> Also, please make sure that AKS node region and storageaccount region are the same so that it won't cause too much network latency.

my  blob account is the same region to aks

**Comment by andyzhangx** [comment]
@vibhansa-msft do you have any guidance about how to make unzip faster based on blobfuse v1 mount, like tuning some mount options?

**Comment by lifejoyforpy** [comment]
my blob-cis-driver   image is mcr.azk8s.cn/oss/kubernetes-csi/blob-csi:v1.16.0。 
i hope can help me. tks

**Comment by lifejoyforpy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lifejoyforpy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lifejoyforpy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
