### ISSUE TITLE
NFS Dynamic Provisioning Failed

### ISSUE THREAD

**Issue by rainerleber** [kubernetes-sigs/blob-csi-driver#772]
**What happened**: Dynamic Provisioning failed with the following error :

 failed to provision volume with StorageClass "nfs-blob-csi": rpc error: code = Internal desc = ensure storage account failed with failed to create storage account nfsde57fe7c1fe84932a8ee, error: &{false 400 0001-01-01 00:00:00 +0000 UTC {"error":{"code":"InvalidValuesForRequestParameters","message":"Values for request parameters are invalid: networkAcls.virtualNetworkRules[*].id. For more information, see - https://aka.ms/storagenetworkruleset"}}}

There is a policy in Azure Defined wich assigns some ACLs dynamically. But this should not impact the dynamic provisioning.

**What you expected to happen**: Dynamic Provisioning of NFS Enabled Storage Account

**How to reproduce it**: 

**Anything else we need to know?**:

- CSI Driver version: 1.16.0
- Kubernetes version (use `kubectl version`): 1.24.4

**Comment by andyzhangx** [comment]
if `storageAccount` is not provided, this driver would try to create a storage account while it may break the policy in ACL setting, I think you could create storageAccount in advance, and set in storage class parameters as `storageAccount: xxx`, that should workaround.

**Comment by rainerleber** [comment]
Hi @andyzhangx thanks for the reply. Yes creating a storage account an then use it will work, but i want a dynamic way so i don't have to take care of creating it.

**Comment by andyzhangx** [comment]
so what's your suggested setting for `networkAcls.virtualNetworkRules`? do you have some examples? I am thinking whether we could set those rules in storage class parameters

**Comment by rainerleber** [comment]
![image](https://user-images.githubusercontent.com/39616583/195291691-4350b5d0-7eb2-4ff6-bd31-00a98937986b.png)

I think the problem is something different the picture above shows a manual create SA and the key virtualNetworkRules have no values. When the csi-driver try to create the SA i think the `virtualNetworkRules` is empty as well but tries to read something from `networkAcls.virtualNetworkRules[*].id` which is not present.

**Comment by andyzhangx** [comment]
what's your `nfs-blob-csi` sc config? and are you using open source driver now?

**Comment by andyzhangx** [comment]
cc @cvvz

**Comment by andyzhangx** [comment]
thanks, this issue should be fixed in next release v1.17.0, the fix is now in master branch.
