### ISSUE TITLE
Broken paths in index.yaml - "master" branch is used instead of release label "v1.17.0"

### ISSUE THREAD

**Issue by MattMcL4475** [kubernetes-sigs/blob-csi-driver#783]
The `index.yaml` file references the `master` branch, instead of the labeled release branch, which results in `helm repo add` failing.  Note: it is best to use labeled release URLs to ensure the link is permanent and not broken if master is changed.  Details:

This file:
https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/v1.17.0/charts/index.yaml

Contains the broken URL:
https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/latest/blob-csi-driver-v1.17.0.tgz

This link is broken.  It is referencing the `master` branch, when instead, it should be referencing the release label `v1.17.0`

Correct URL:
https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/v1.17.0/charts/latest/blob-csi-driver-v1.17.0.tgz

Because of this, when you do:
`helm repo add https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/v1.17.0/charts`

Helm will fail with this:
failed to fetch https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/latest/blob-csi-driver-v1.17.0.tgz : 404 Not Found

**Comment by andyzhangx** [comment]
should be fixed by https://github.com/kubernetes-sigs/blob-csi-driver/commit/476b3f49fdccce5f72a3a428fdbb82861273626f, pls try again, thanks.

And usually we won't change released chart file, so it's safe to run `helm repo add blob-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts`

**Comment by MattMcL4475** [comment]
This is broken again for v1.18.0.  This file:

https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/v1.18.0/charts/index.yaml

Contains the broken link:

https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/latest/blob-csi-driver-v1.18.0.tgz

**Comment by andyzhangx** [comment]
> helm repo add blob-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts

@MattMcL4475 are you able to install helm chart on master branch? 
```
helm repo add blob-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts
```
