### ISSUE TITLE
blobfuse-proxy support core os (OpenShift)

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/blob-csi-driver#791]
**Is your feature request related to a problem?/Why is this needed**

Currently blobfuse-proxy is only available on debian based agent node, it's not supported on core os (OpenShift)

https://github.com/kubernetes-sigs/blob-csi-driver/tree/master/deploy/blobfuse-proxy

**Describe the solution you'd like in detail**

**Describe alternatives you've considered**

**Additional context**

**Comment by cvvz** [comment]
I've done some investigation on openshift and coreos, here is the conclusion:

CoreOS doesn't support install software after the node up. Although you can use [rpm-ostree install](https://coreos.github.io/rpm-ostree/administrator-handbook/#hybrid-imagepackaging-via-package-layering) to install rpm package (add additional “layered” packages), it will only take effect when you reboot. And the version of the `rpm-ostree` on ARO worker node is too old to support `live-apply`. 

CoreOS provides the mechanism called [igition](https://coreos.github.io/ignition/rationale/) to set up the machine, but it runs only on the first boot. And it's not able to create an ARO cluster with custom ignition configuration.

Openshift provides the mechanism called [Machine Config Operator](https://docs.openshift.com/container-platform/4.8/post_installation_configuration/machine-configuration-tasks.html#understanding-the-machine-config-operator), which support "manages and applies configuration and updates of the base operating system", but we cannot use it to install software on the node neither.

IMO, there is only one way to achieve the goal (which is install blobfuse/blobfuse2/blobfuse-proxy and other dependencies and start the blobfuse-proxy service on the node): Build a base system image which includes all the software we need( blobfuse, blobfuse2, blobfuse-proxy and other dependencies), and use it to create ARO worker node pool, sounds like VHD to AKS worker nodes.

**Comment by jsafrane** [comment]
/reopen
I commented on https://github.com/Azure/azure-storage-fuse/issues/766#issuecomment-1748689065, the real CoreOS work needs to be done in this repository.

**Comment by cvvz** [comment]
Hi @jsafrane thanks for your advice, I have another question: what if we want to update the dependencies of blobfuse2? We still have to upgrade the node image and reboot, but for now, we can just install blobfuse2 itself and it will just work fine, am I correct?

**Comment by jsafrane** [comment]
I am not sure I understand the question, blobfuse2 is statically linked, so what dependencies do you mean? The official microsoft RPM requires only `fuse3` and yes, you get any of `fuse3` updates via CoreOS update, which will be done as part of OpenShift update process. You should not worry about updating that and you should not depend on a specific `fuse3` version either.

**Comment by cvvz** [comment]
I got it, thanks!
