### ISSUE TITLE
Not able to install v1.18.0 using "az aks ..." command

### ISSUE THREAD

**Issue by mortenjoenby** [kubernetes-sigs/blob-csi-driver#798]
**What happened**:
We are using v1.17.0 but would like to use Blobfuse2.
Trying to "upgrade" to v1.18.0 using "az aks update --enable-blob-driver -n myAKSCluster -g myResourceGroup" does not update it.
We also tried to disable and enable again. Still v1.17.0.

**What you expected to happen**:
Version 1.18.0 to be available.

**How to reproduce it**:
Try running the "az aks udate ..." command.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 1.17.0
- Kubernetes version (use `kubectl version`): 1.24.3

**Comment by andyzhangx** [comment]
`v1.18.0` version is still rolling out, it's ready in canary regions(`centraluseuap`, `eastus2euap`) now, you could try on these two regions. btw, using `az aks update` command won't do the blob csi driver version upgrade since the version is managed by AKS.

**Comment by mortenjoenby** [comment]
Hi Andy.
So what is the expected rollout plan? We use westeurope, eastus and japaneast only at the moment.
And will the version then be upgraded automatically?
Thanks for your quick feedback!

**Comment by andyzhangx** [comment]
> Hi Andy. So what is the expected rollout plan? We use westeurope, eastus and japaneast only at the moment. And will the version then be upgraded automatically? Thanks for your quick feedback!

@mortenjoenby the version will be upgraded automatically, it should be upgraded in this month, while due to the holiday season, there is limitation of AKS rollout, I cannot provide the exact date for those regions, thanks for understanding.
I think you could try on `eastus2euap` region for testing purpose, thanks.

**Comment by andyzhangx** [comment]
v1.18.0 version which supports blobfuse2 is already rolled out complete in `eastus` region now.

**Comment by andyzhangx** [comment]
close this issue since v1.18.0 has been rolled out to all azure public regions now.

**Comment by andyzhangx** [comment]
to install v2.0.1 blobfuse version, you could also run following command on AKS cluster directly:
```console
kubectl patch daemonset csi-blob-node -n kube-system -p '{"spec":{"template":{"spec":{"initContainers":[{"env":[{"name":"INSTALL_BLOBFUSE","value":"true"},{"name":"BLOBFUSE_VERSION","value":"1.4.5"}],"name":"install-blobfuse-proxy"}]}}}}'
```
