### ISSUE TITLE
Mounting container blob inside a pod on Openshift

### ISSUE THREAD

**Issue by abudavis** [kubernetes-sigs/blob-csi-driver#817]
Our goal is to mount the files inside an Azure blob container on a pod on Openshift.

I did not quite understand where to supply the the SAS URL + SAS key for from the azure blob container (that sits inside a storage account) for accessing the files inside the container.

This is my starting point, am I supposed to edit the yamls or do the install as directed? - https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/install-csi-driver-v1.19.0.md

- CSI Driver version: 1.19
- Openshift 4.10.30

**Comment by andyzhangx** [comment]
to install this driver on OpenShift, pls follow: https://github.com/ezYakaEagle442/aro-pub-storage/blob/master/setup-store-CSI-driver-azure-blob.md

**Comment by abudavis** [comment]
Thank you!
