### ISSUE TITLE
[BUG] blobfuse2 aks 1.25.5 fail with isHnsEnabled=true after upgrade from aks 1.24.9

### ISSUE THREAD

**Issue by aresabalo** [kubernetes-sigs/blob-csi-driver#837]
**Describe the bug
Fail usage blobfuse2 with csi driver in aks 1.25

**To Reproduce

Mount volume aks 1.25 with fuse2 protocol and blog storage account with "Hierarchical namespace" activated

...
volumes:
- name: repositorio-web-vol
csi:
driver: blob.csi.azure.com
readOnly: false
volumeAttributes:
secretName: blob-storage-public-secrets
containerName: web-repository
protocol: fuse2
isHnsEnabled: "true"
mountOptions: "-o allow_other --file-cache-timeout-in-seconds=120 --use-attr-cache=true --cancel-list-on-mount-seconds=60 -o attr_timeout=120 -o entry_timeout=120 -o negative_timeout=120"
....

Error renaming files on volumed mounted with blobfuse2 in pod terminal:

mv file.txt file2.txt
mv: can't rename 'file.txt': I/O error

I can read files, but fail renaming files.

**Expected behavior
It's ok with aks 1.24.9. Fail after upgrade to aks 1.25.5

**Environment

    Kubernetes version 1.25.5
    Image AKSUbuntu-2204gen2containerd-2023.02.15
    image: mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.19.0

**Comment by andyzhangx** [comment]
let's track this issue in blobfuse repo: https://github.com/Azure/azure-storage-fuse/issues/1080#issuecomment-1463701773
