### ISSUE TITLE
support AzureStorageAuthType SPN with Inline volume

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/blob-csi-driver#840]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

related to https://github.com/kubernetes-sigs/blob-csi-driver/discussions/839

**Describe alternatives you've considered**

**Additional context**

**Comment by PLCyr** [comment]
We try not to rely too much on PersistentVolumes because we have limited access to cluster wide ressources. Being able to use SPN authentication with AzureBlob with Inline Volume would be great !

**Comment by andyzhangx** [comment]
this feature is already supported in blob csi driver version v1.21.0 on AKS 1.26
