### ISSUE TITLE
Failed to pull image "mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.21.0 on AKS.1.26.0+

### ISSUE THREAD

**Issue by lturmel** [kubernetes-sigs/blob-csi-driver#880]
Failed to pull image "mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.21.0" on aks v1.26.0+
Which is currently blocking creation of any AKS clusters with v1.26.0+
AKS VmScaleSet SKU: standard_d2ps_v5 (ARM64)

**What happened**:
Failed to pull image "mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.21.0": rpc error: code = NotFound desc = failed to pull and unpack image "mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.21.0": failed to resolve reference "mcr.microsoft.com/os ││ s/kubernetes-csi/blob-csi:v1.21.0": mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.21.0: not found 

**What you expected to happen**:
Succesfull pull mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.21.0

**How to reproduce it**:
Create a AKS Cluster with k8s version 1.26.0+ with node base on ARM64 (sku: standard_d2ps_v5)

**Anything else we need to know?**:

**Environment**:

image: mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.21.0
      image: mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.21.0
    - image: mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.21.0
    - image: mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.21.0
            "mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.21.0": failed to resolve
            reference "mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.21.0": mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.21.0:

**Comment by andyzhangx** [comment]
thanks for reporting this issue.
`mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.21.0` image is ready now

**Comment by andyzhangx** [comment]
btw, blobfuse mount does not support arm64, only nfs mount is supported by blob csi driver.
