### ISSUE TITLE
Failed to init csi-blob-node pods

### ISSUE THREAD

**Issue by satr** [kubernetes-sigs/blob-csi-driver#998]
**What happened**:
When install driver 1.22.1 with flux on new or upgraded cluster, pods od ds csi-blob-node failed to init. Such pods on another cluster continue working. Downgraded driver to 1.21.4 works fine. 

**What you expected to happen**:
Pods start and run without error

**How to reproduce it**:
Install the driver v1.22.1 to a Azure AKS cluster or upgrade existing driver to it.

**Anything else we need to know?**:
When run in a custom pod command `/blobfuse-proxy/init.sh` in the image `mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.22.1` it fails with an error:
```
# ls
bin  blobfuse-proxy  blobplugin  boot  dev  etc  home  host  lib  lib64  media	mnt  opt  proc	root  run  sbin  srv  sys  tmp	usr  var
# /blobfuse-proxy/init.sh
+ INSTALL_BLOBFUSE_PROXY=true
+ DISABLE_UPDATEDB=true
+ SET_MAX_OPEN_FILE_NUM=true
+ SET_READ_AHEAD_SIZE=true
+ READ_AHEAD_KB=15380
+ HOST_CMD=nsenter --mount=/proc/1/ns/mnt
.......
+ [ 0 -eq 1 ]
+ echo install fuse3 for blobfuse2, current release is 22.04
install fuse3 for blobfuse2, current release is 22.04
+ pkg_list= fuse3
+ [ -z 2.0.3 ]
+ pkg_list= fuse3 blobfuse2=2.0.3
+ echo begin to install  fuse3 blobfuse2=2.0.3
begin to install  fuse3 blobfuse2=2.0.3
+ nsenter --mount=/proc/1/ns/mnt apt-get install -y fuse3 blobfuse2=2.0.3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fuse3 is already the newest version (3.10.5-1build1).
The following packages were automatically installed and are no longer required:
  bc python3-automat python3-bcrypt python3-click python3-colorama python3-constantly python3-hamcrest python3-hyperlink python3-incremental
  python3-pyasn1 python3-pyasn1-modules python3-service-identity python3-twisted python3-zope.interface
Use 'apt autoremove' to remove them.
The following packages will be DOWNGRADED:
  blobfuse2
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 24 not upgraded.
E: Packages were downgraded and -y was used without --allow-downgrades.
# echo $?
100
```

**Environment**:

```
      image: mcr.microsoft.com/k8s/flexvolume/blobfuse-flexvolume:1.0.18
      imageID: mcr.microsoft.com/k8s/flexvolume/blobfuse-flexvolume@sha256:c11c3949209292e77b013d394ec3dcb48f983a591b8ee80c61d6d525d3e638f8
      image: mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.22.1
```
- CSI Driver version: 1.22.1
- Kubernetes version (use `kubectl version`): 1.25.6
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
pls run `kubectl edit ds -n kube-system csi-blob-node` and then set `INSTALL_BLOBFUSE2` env var as `false`, it would work: 

https://github.com/kubernetes-sigs/blob-csi-driver/blob/23765a6bea606905f70475bcd2872c3f10abb062/deploy/v1.22.1/csi-blob-node.yaml#L58-L61

blobfuse2 is already installed by default on AKS node (latest version is v2.0.5)

**Comment by satr** [comment]
It works, thank you!

**Comment by mintLiquor** [comment]
@andyzhangx  Hi Andy, may I know how to prevent this kinda error when installing? I tried "--set node.installBlobfuse2=false" but it did not work.

**Comment by andyzhangx** [comment]
`--set node.installBlobfuse2=false` does not exist any more, what's your blob csi driver pod description? are you using blobfuse-proxy or not? if yes, you could set `--set.node.blobfuseProxy.installBlobfuse2=false` to disable blobfuse2 install on the node

**Comment by mintLiquor** [comment]
> `--set node.installBlobfuse2=false` does not exist any more, what's your blob csi driver pod description? are you using blobfuse-proxy or not? if yes, you could set `--set.node.blobfuseProxy.installBlobfuse2=false` to disable blobfuse2 install on the node

@andyzhangx Many thanks! `--set.node.blobfuseProxy.installBlobfuse2=false` did work! BTW, does this issue(fail to init csi-blob-node pods) still exist when installing the latest csi driver on the latest version of AKS?

**Comment by andyzhangx** [comment]
@mintLiquor if you use AKS managed blob csi driver, installBlobfuse2 is false by default, so it won't have such issue. while if you install open source csi driver, installBlobfuse2 is true by default.

**Comment by mintLiquor** [comment]
@andyzhangx Thanks Andy! It really helps!
